Repository pingcap/docs-dm, pull requests merged in 2020-04, with the labels that each got.

#15 README: update doc versions and branch info
  README.md
Labels: needs-cherry-pick-1.0, translation/no-need

#17 en, zh: add multi_level_url metadata
  en/releases/1.0.2.md
  en/releases/1.0.3.md
  en/releases/1.0.4.md
  zh/releases/1.0.2.md
  zh/releases/1.0.3.md
  zh/releases/1.0.4.md
Labels: needs-cherry-pick-1.0, size/small, translation/no-need

#10 zh: merge the description of OSC and DM online-ddl-scheme into one section
  zh/feature-online-ddl-scheme.md
Labels: needs-cherry-pick-1.0, status/LGT2, translation/doing

#20 en, zh, assets: update get started
  assets/get-started/dm-cnf.tgz
  en/get-started.md
  zh/get-started.md
Labels: status/LGT1, status/LGT2, status/PTAL, translation/done

#25 zh: update dm-worker config doc for 2.0
  zh/dm-worker-configuration-file-full.md
  zh/dm-worker-configuration-file.md
Labels: needs-cherry-pick-2.0, priority/P1, status/PTAL, translation/doing, v2.0

#26 zh: update dm-master config doc for 2.0
  zh/dm-master-configuration-file.md
Labels: needs-cherry-pick-2.0, priority/P1, status/PTAL, translation/doing, v2.0

#28 zh: update task config for 2.0
  zh/task-configuration-file-full.md
  zh/task-configuration-file.md
Labels: needs-cherry-pick-2.0, priority/P1, status/LGT1, translation/doing, v2.0

#27 zh: add source-configuration-file.md for 2.0
  zh/source-configuration-file.md
Labels: needs-cherry-pick-2.0, priority/P1, status/LGT1, translation/doing, v2.0

#30 zh: update overview.md to 2.0
  media/dm-architecture-2.0.png
  zh/overview.md
Labels: needs-cherry-pick-2.0, priority/P2, status/PTAL, status/can-merge, translation/doing, v2.0

#29 zh: update config-overview.md for 2.0
  zh/config-overview.md
Labels: follow-up, needs-cherry-pick-2.0, priority/P1, translation/doing, v2.0

#31 zh: add more explanation in feature-overview.md
  zh/feature-overview.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, translation/doing

#37 en: add more explanation in feature-overview.md
  en/feature-overview.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, status/PTAL, translation/from-zh

#35 zh: update manage-replication-tasks.md for 2.0
  zh/manage-replication-tasks.md
Labels: needs-cherry-pick-2.0, priority/P2, status/LGT2, translation/doing, v2.0

#33 zh: update get-started.md for 2.0
  assets/get-started/dm-cnf.tgz
  zh/get-started.md
Labels: needs-cherry-pick-2.0, priority/P2, status/LGT1, translation/doing, v2.0

#43 zh: Add config change example
  zh/task-configuration-file.md
Labels: needs-cherry-pick-1.0, status/LGT1, translation/doing, v2.0

#41 zh: update deploy-a-dm-cluster-using-binary for 2.0
  zh/deploy-a-dm-cluster-using-binary.md
Labels: priority/P2, status/LGT1, translation/doing, v2.0

#45 zh: update monitor-a-dm-cluster.md for 2.0
  zh/monitor-a-dm-cluster.md
Labels: priority/P2, status/LGT2, v2.0

#51 en: update overview.md for 2.0
  en/overview.md
Labels: priority/P2, translation/from-zh, v2.0

#36 en: update dm-master config doc for 2.0
  en/dm-master-configuration-file.md
Labels: priority/P1, status/PTAL, status/can-merge, translation/from-zh, v2.0

#34 en: update dm-worker config doc for 2.0
  en/dm-worker-configuration-file-full.md
  en/dm-worker-configuration-file.md
  en/relay-log.md
Labels: priority/P1, status/PTAL, translation/from-zh, v2.0

#53 en: update deploy-a-dm-cluster-using-binary for 2.0
  en/deploy-a-dm-cluster-using-binary.md
Labels: priority/P2, status/LGT2, translation/from-zh, v2.0

#54 zh: add more heartbeat information in task-configuration-file-full.md
  zh/task-configuration-file-full.md
Labels: priority/P1, status/LGT2, translation/doing, v2.0

#49 zh: fix errors in manage-replication-tasks.md
  zh/manage-replication-tasks.md
Labels: status/LGT1, v2.0

#56 en: update the wording of dm-worker & dm-master config files
  en/dm-master-configuration-file.md
  en/dm-worker-configuration-file.md
Labels: translation/no-need, v2.0

#38 en: add source-configuration-file.md for 2.0
  en/source-configuration-file.md
Labels: priority/P1, status/can-merge, translation/from-zh, v2.0

#47 TOC: add source-configuration-file.md for 2.0
  en/TOC.md
  zh/TOC.md
Labels: translation/no-need, v2.0

#57 en: update monitor-a-dm-cluster.md for 2.0
  en/monitor-a-dm-cluster.md
Labels: needs-cherry-pick-1.0, priority/P2, status/PTAL, status/can-merge, translation/from-zh, v2.0

#59 release: add release notes for v1.0.5
  en/TOC.md
  en/releases/1.0.5.md
  zh/TOC.md
  zh/releases/1.0.5.md
Labels: needs-cherry-pick-1.0, status/PTAL

#52 en: update get-started.md for 2.0
  en/get-started.md
Labels: priority/P2, status/LGT2, status/can-merge, translation/from-zh, v2.0

#46 en: update task config for 2.0
  en/task-configuration-file-full.md
  en/task-configuration-file.md
Labels: priority/P1, status/LGT1, status/can-merge, translation/from-zh, v2.0

#62 en: add config change example
  en/task-configuration-file.md
Labels: needs-cherry-pick-1.0, status/can-merge, translation/from-zh, v2.0

#48 en: update manage-replication-tasks.md for 2.0
  en/manage-replication-tasks.md
Labels: priority/P2, status/can-merge, translation/from-zh, v2.0
