Repository pingcap/docs-dm, pull requests merged in 2020-09, with the labels that each got.

#328 Update replicate-data-using-dm.md
  en/replicate-data-using-dm.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, size/small, status/LGT2, status/can-merge, translation/from-zh

#327 en: update join config
  en/dm-worker-configuration-file.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#306 zh: Update descriptions about 迁移 & 同步 to make it clearer
  zh/TOC.md
  zh/_index.md
  zh/alert-rules.md
  zh/benchmark-v1.0-ga.md
  zh/config-overview.md
  zh/create-task.md
  zh/dm-worker-intro.md
  zh/dmctl-introduction.md
  zh/error-handling.md
  zh/faq.md
  zh/feature-online-ddl-scheme.md
  zh/feature-shard-merge-optimistic.md
  zh/feature-shard-merge-pessimistic.md
  zh/feature-shard-merge.md
  zh/glossary.md
  zh/handle-failed-sql-statements.md
  zh/handle-performance-issues.md
  zh/hardware-and-software-requirements.md
  zh/key-features.md
  zh/manually-handling-sharding-ddl-locks.md
  zh/manually-upgrade-dm-1.0-to-2.0.md
  zh/migrate-data-using-dm.md
  zh/migrate-from-mysql-aurora.md
  zh/monitor-a-dm-cluster.md
  zh/overview.md
  zh/pause-task.md
  zh/performance-test.md
  zh/precheck.md
  zh/query-status.md
  zh/quick-start-create-task.md
  zh/relay-log.md
  zh/releases/1.0.3.md
  zh/releases/1.0.4.md
  zh/releases/1.0.5.md
  zh/releases/2.0.0-rc.md
  zh/resume-task.md
  zh/scenarios.md
  zh/shard-merge-best-practices.md
  zh/stop-task.md
  zh/task-configuration-file-full.md
  zh/task-configuration-file.md
  zh/tune-configuration.md
  zh/upgrade-dm-1.0.md
  zh/usage-scenario-downstream-more-columns.md
  zh/usage-scenario-simple-migration.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, size/large, status/LGT2, status/PTAL, status/can-merge, translation/done

#331 *: add v2.0.0-rc.2 release notes
  en/TOC.md
  en/releases/2.0.0-rc.2.md
  zh/TOC.md
  zh/releases/2.0.0-rc.2.md
Labels: needs-cherry-pick-2.0, status/LGT2, translation/done

#342 zh: add some notices about connectivity
  zh/deploy-a-dm-cluster-using-binary.md
  zh/deploy-a-dm-cluster-using-tiup.md
  zh/maintain-dm-using-tiup.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT1, translation/doing

#345 Add 4 aliases to fix dead links
  en/overview.md
  en/task-configuration-file-full.md
  zh/manage-replication-tasks.md
  zh/releases/1.0.5.md
Labels: status/LGT1, status/PTAL, translation/no-need, type/bug-fix

#346 add ci job to check unclosed tags
  .github/workflows/ci.yaml
  en/task-configuration-file.md
  hack/check-tags.py
  zh/overview.md
Labels: translation/done

#344 *: refine docs about binlog GTID
  en/source-configuration-file.md
  en/task-configuration-file-full.md
  zh/source-configuration-file.md
  zh/task-configuration-file-full.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT1, status/PTAL, translation/no-need

#312 en: Update descriptions about 迁移 & 同步 to make it clearer
  en/TOC.md
  en/_index.md
  en/alert-rules.md
  en/config-overview.md
  en/create-task.md
  en/dm-worker-intro.md
  en/dmctl-introduction.md
  en/error-handling.md
  en/faq.md
  en/feature-online-ddl-scheme.md
  en/feature-shard-merge-optimistic.md
  en/feature-shard-merge-pessimistic.md
  en/feature-shard-merge.md
  en/glossary.md
  en/handle-failed-sql-statements.md
  en/handle-performance-issues.md
  en/hardware-and-software-requirements.md
  en/key-features.md
  en/manage-schema.md
  en/manually-handling-sharding-ddl-locks.md
  en/manually-upgrade-dm-1.0-to-2.0.md
  en/migrate-data-using-dm.md
  en/migrate-from-mysql-aurora.md
  en/monitor-a-dm-cluster.md
  en/overview.md
  en/pause-task.md
  en/performance-test.md
  en/precheck.md
  en/quick-start-create-task.md
  en/relay-log.md
  en/releases/1.0.2.md
  en/releases/1.0.3.md
  en/releases/1.0.4.md
  en/releases/1.0.5.md
  en/resume-task.md
  en/scenarios.md
  en/shard-merge-best-practices.md
  en/stop-task.md
  en/task-configuration-file-full.md
  en/task-configuration-file.md
  en/tune-configuration.md
  en/upgrade-dm-1.0.md
  en/usage-scenario-master-slave-switch.md
  en/usage-scenario-simple-migration.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, size/large, status/LGT2, status/PTAL, translation/from-zh, version-specific-changes-required

#326 Add warning for import cmd
  en/maintain-dm-using-tiup.md
Labels: needs-cherry-pick-2.0, require-LGT1, size/small, status/LGT1, status/can-merge, status/require-change, translation/from-zh

#319 Update deploy-a-dm-cluster-using-tiup.md
  zh/deploy-a-dm-cluster-using-tiup.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT2, status/can-merge, status/require-change, translation/doing

#353 *: check link via GitHub action
  .github/workflows/ci.yaml
  .github/workflows/link-check.yaml
  en/maintain-dm-using-tiup.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, status/LGT1, translation/no-need

#348 zh: add a notice about topology example for scale-out
  zh/maintain-dm-using-tiup.md
Labels: needs-cherry-pick-2.0, require-LGT1, size/small, status/LGT1, status/can-merge, translation/doing

#360 Update maintain-dm-using-tiup.md
  en/maintain-dm-using-tiup.md
  zh/maintain-dm-using-tiup.md
Labels: require-LGT1, size/small, status/LGT1, status/can-merge, translation/no-need

#362 Add 7 aliases to fix dead links
  en/cluster-operations.md
  en/glossary.md
  en/usage-scenario-simple-replication.md
  zh/releases/1.0.2.md
  zh/releases/1.0.5.md
  zh/task-configuration-file.md
  zh/usage-scenario-simple-replication.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#358 en: Update descriptions about 迁移 & 同步 to make it clearer in DM 1.0
  en/TOC.md
  en/_index.md
  en/alert-rules.md
  en/benchmark-v1.0-ga.md
  en/cluster-operations.md
  en/config-overview.md
  en/deploy-a-dm-cluster-using-ansible.md
  en/deploy-a-dm-cluster-using-binary.md
  en/dm-portal.md
  en/dm-upgrade.md
  en/dm-worker-configuration-file-full.md
  en/dm-worker-configuration-file.md
  en/dm-worker-intro.md
  en/error-handling.md
  en/faq.md
  en/feature-manually-handling-sharding-ddl-locks.md
  en/feature-overview.md
  en/feature-shard-merge.md
  en/get-started.md
  en/glossary.md
  en/handle-performance-issues.md
  en/manage-migration-tasks.md
  en/migrate-data-using-dm.md
  en/migrate-from-mysql-aurora.md
  en/monitor-a-dm-cluster.md
  en/overview.md
  en/precheck.md
  en/query-status.md
  en/relay-log.md
  en/releases/1.0.2.md
  en/releases/1.0.3.md
  en/releases/1.0.4.md
  en/releases/1.0.5.md
  en/shard-merge-best-practices.md
  en/skip-or-replace-abnormal-sql-statements.md
  en/task-configuration-file-full.md
  en/task-configuration-file.md
  en/usage-scenario-master-slave-switch.md
  en/usage-scenario-simple-migration.md
  zh/TOC.md
  zh/alert-rules.md
  zh/config-overview.md
  zh/manage-migration-tasks.md
  zh/migrate-data-using-dm.md
  zh/monitor-a-dm-cluster.md
  zh/overview.md
  zh/usage-scenario-simple-migration.md
Labels: size/large, status/LGT2, status/PTAL, type/1.0-cherry-pick

#370 *: add exit_code check for zh link checking
  .github/workflows/link-check.yaml
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, status/LGT1, translation/no-need

#368 Update deploy-a-dm-cluster-using-tiup.md
  en/deploy-a-dm-cluster-using-tiup.md
Labels: needs-cherry-pick-2.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/from-zh

#369 en: add a notice about topology example for scale-out
  en/maintain-dm-using-tiup.md
Labels: needs-cherry-pick-2.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/from-zh

#363 Add hints for using plaintext passwords
  en/quick-start-create-task.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, size/small, status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#378 Add hints for using plaintext passwords (#363)
  en/deploy-a-dm-cluster-using-ansible.md
Labels: size/small, status/LGT2, status/PTAL, type/1.0-cherry-pick

#380 Fix a format issue
  zh/migrate-from-mysql-aurora.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT1, translation/done

#364 en: add notices about import/scale with TiUP
  en/maintain-dm-using-tiup.md
Labels: needs-cherry-pick-2.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/from-zh

#367 en: add some notices about connectivity
  en/deploy-a-dm-cluster-using-binary.md
  en/deploy-a-dm-cluster-using-tiup.md
  en/maintain-dm-using-tiup.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#366 en: add a simpe desc about HA
  en/_index.md
  en/overview.md
Labels: needs-cherry-pick-2.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/from-zh

#350 zh: update some steps to resolve problems
  zh/deploy-a-dm-cluster-using-tiup.md
  zh/faq.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT2, status/PTAL, status/can-merge, translation/doing

#382 zh, en: update Aurora migration doc
  en/migrate-from-mysql-aurora.md
  zh/migrate-from-mysql-aurora.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT2, status/can-merge, translation/no-need

#379 zh: some mirror updates
  zh/deploy-a-dm-cluster-using-tiup.md
  zh/dm-worker-intro.md
  zh/glossary.md
  zh/key-features.md
  zh/overview.md
  zh/task-configuration-file-full.md
Labels: needs-cherry-pick-2.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing

#377 en: Update doc for aurora migration
  en/deploy-a-dm-cluster-using-tiup.md
  en/hardware-and-software-requirements.md
  en/migrate-from-mysql-aurora.md
Labels: needs-cherry-pick-2.0, size/medium, status/LGT1, status/PTAL, translation/from-zh

#392 en: some mirror updates
  en/dm-worker-intro.md
  en/glossary.md
  en/key-features.md
  en/overview.md
  en/task-configuration-file-full.md
Labels: needs-cherry-pick-2.0, status/LGT2, status/PTAL, translation/from-zh

#393 en: update some steps to resolve problems
  en/deploy-a-dm-cluster-using-tiup.md
  en/faq.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#398 Add 8 aliases to fix dead links
  en/error-handling.md
  en/overview.md
  en/releases/1.0.3.md
  zh/deploy-a-dm-cluster-using-ansible.md
  zh/dm-worker-intro.md
  zh/error-handling.md
  zh/feature-shard-merge.md
  zh/releases/1.0.2.md
Labels: status/LGT1, translation/no-need, type/bug-fix
