Repository pingcap/docs-dm, pull requests merged in 2020-08, with the labels that each got.

#202 .github: add cherry-pick checklist in pr template
  .github/pull_request_template.md
Labels: needs-cherry-pick-1.0, status/LGT1, translation/no-need

#204 en: add 3 aliases to fix 3 dead links
  en/cluster-operations.md
  en/manage-replication-tasks.md
  en/table-selector.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#198 Update faq.md
  en/faq.md
Labels: needs-cherry-pick-1.0, status/LGT2, status/PTAL, translation/from-zh

#192 en: add usage-scenario-master-slave-switch.md
  en/TOC.md
  en/_index.md
  en/cluster-operations.md
  en/overview.md
  en/usage-scenario-master-slave-switch.md
Labels: needs-cherry-pick-1.0, status/LGT1, translation/no-need

#194 Update a sentence in scenarios.md
  en/scenarios.md
Labels: status/LGT1, translation/no-need

#207 Add aliases to 60 files on master branch
  zh/_index.md
  zh/alert-rules.md
  zh/benchmark-v1.0-ga.md
  zh/cluster-operations.md
  zh/command-line-flags.md
  zh/config-overview.md
  zh/create-task.md
  zh/daily-check.md
  zh/deploy-a-dm-cluster-using-ansible.md
  zh/deploy-a-dm-cluster-using-binary.md
  zh/dm-master-configuration-file.md
  zh/dm-portal.md
  zh/dm-worker-configuration-file.md
  zh/dm-worker-intro.md
  zh/dmctl-introduction.md
  zh/error-handling.md
  zh/faq.md
  zh/feature-online-ddl-scheme.md
  zh/feature-shard-merge-optimistic.md
  zh/feature-shard-merge-pessimistic.md
  zh/feature-shard-merge.md
  zh/glossary.md
  zh/handle-alerts.md
  zh/handle-performance-issues.md
  zh/hardware-and-software-requirements.md
  zh/key-features.md
  zh/manage-source.md
  zh/manually-handling-sharding-ddl-locks.md
  zh/manually-upgrade-dm-1.0-to-2.0.md
  zh/migrate-from-mysql-aurora.md
  zh/monitor-a-dm-cluster.md
  zh/overview.md
  zh/pause-task.md
  zh/performance-test.md
  zh/precheck.md
  zh/query-error.md
  zh/query-status.md
  zh/quick-start-create-task.md
  zh/quick-start-with-dm.md
  zh/relay-log.md
  zh/releases/1.0.2.md
  zh/releases/1.0.3.md
  zh/releases/1.0.4.md
  zh/releases/1.0.5.md
  zh/releases/1.0.6.md
  zh/replicate-data-using-dm.md
  zh/resume-task.md
  zh/scenarios.md
  zh/shard-merge-best-practices.md
  zh/skip-or-replace-abnormal-sql-statements.md
  zh/source-configuration-file.md
  zh/stop-task.md
  zh/table-selector.md
  zh/task-configuration-file-full.md
  zh/task-configuration-file.md
  zh/tune-configuration.md
  zh/upgrade-dm-1.0.md
  zh/usage-scenario-master-slave-switch.md
  zh/usage-scenario-shard-merge.md
  zh/usage-scenario-simple-replication.md
Labels: status/LGT1, translation/no-need

#208 Add aliases to 44 files on release-1.0 branch
  zh/_index.md
  zh/alert-rules.md
  zh/benchmark-v1.0-ga.md
  zh/cluster-operations.md
  zh/config-overview.md
  zh/deploy-a-dm-cluster-using-ansible.md
  zh/deploy-a-dm-cluster-using-binary.md
  zh/dm-master-configuration-file.md
  zh/dm-portal.md
  zh/dm-upgrade.md
  zh/dm-worker-configuration-file-full.md
  zh/dm-worker-configuration-file.md
  zh/dm-worker-intro.md
  zh/error-handling.md
  zh/faq.md
  zh/feature-manually-handling-sharding-ddl-locks.md
  zh/feature-online-ddl-scheme.md
  zh/feature-overview.md
  zh/feature-shard-merge.md
  zh/get-started.md
  zh/glossary.md
  zh/handle-alerts.md
  zh/handle-performance-issues.md
  zh/manage-replication-tasks.md
  zh/migrate-from-mysql-aurora.md
  zh/monitor-a-dm-cluster.md
  zh/overview.md
  zh/precheck.md
  zh/query-status.md
  zh/relay-log.md
  zh/releases/1.0.2.md
  zh/releases/1.0.3.md
  zh/releases/1.0.4.md
  zh/releases/1.0.5.md
  zh/releases/1.0.6.md
  zh/replicate-data-using-dm.md
  zh/shard-merge-best-practices.md
  zh/skip-or-replace-abnormal-sql-statements.md
  zh/table-selector.md
  zh/task-configuration-file-full.md
  zh/task-configuration-file.md
  zh/usage-scenario-master-slave-switch.md
  zh/usage-scenario-shard-merge.md
  zh/usage-scenario-simple-replication.md
Labels: status/LGT1, translation/no-need

#210 Fix a deadlink in dm doc
  zh/releases/1.0.4.md
Labels: needs-cherry-pick-1.0, status/LGT1, translation/no-need, type/bug-fix, version-specific-changes-required

#212 Fix a typo in alias
  zh/releases/1.0.4.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#214 zh: update download
  zh/deploy-a-dm-cluster-using-binary.md
Labels: needs-cherry-pick-1.0, status/LGT1, status/PTAL

#217 Update deploy-a-dm-cluster-using-binary.md
  en/deploy-a-dm-cluster-using-binary.md
Labels: needs-cherry-pick-1.0, status/LGT2, status/PTAL, translation/from-zh

#209 add Scenario Description
  zh/usage-scenario-shard-merge.md
Labels: needs-cherry-pick-1.0, size/small, status/LGT2, status/PTAL, translation/doing

#219 add `operate-source show`
  zh/dmctl-introduction.md
  zh/manage-source.md
Labels: size/small, status/LGT1, status/PTAL, translation/doing, v2.0

#237 en, zh: add 5 links to fix dead links
  en/benchmark-v1.0-ga.md
  en/error-handling.md
  en/usage-scenario-shard-merge.md
  zh/benchmark-v1.0-ga.md
  zh/error-handling.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#228 zh,en: update tls config
  en/dm-master-configuration-file.md
  en/dm-worker-configuration-file.md
  en/source-configuration-file.md
  en/task-configuration-file-full.md
  zh/dm-master-configuration-file.md
  zh/dm-worker-configuration-file.md
  zh/source-configuration-file.md
  zh/task-configuration-file-full.md
Labels: status/LGT1, status/PTAL, translation/no-need, v2.0

#221 update notes for dmctl
  zh/dmctl-introduction.md
Labels: require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing, v2.0

#232 zh: remove contents about DM-portal
  zh/TOC.md
  zh/dm-portal.md
  zh/task-configuration-file-full.md
Labels: status/LGT1, status/PTAL, translation/welcome, v2.0, version-specific-changes-required

#220 support using task-file when need task-name
  zh/dmctl-introduction.md
  zh/pause-task.md
  zh/resume-task.md
  zh/stop-task.md
  zh/task-configuration-file.md
Labels: needs-cherry-pick-1.0, size/small, status/LGT1, status/PTAL, translation/doing, v2.0

#223 zh, en: add primary/unique key check description
  en/precheck.md
  zh/precheck.md
Labels: needs-cherry-pick-1.0, require-LGT1, status/LGT1, status/can-merge, translation/no-need

#238 zh: fix contents about encryption of passwords
  zh/feature-online-ddl-scheme.md
  zh/migrate-from-mysql-aurora.md
  zh/quick-start-create-task.md
  zh/replicate-data-using-dm.md
  zh/source-configuration-file.md
  zh/task-configuration-file.md
Labels: size/small, status/PTAL, translation/welcome, v2.0

#231 zh: update contents about relay
  zh/TOC.md
  zh/dm-worker-intro.md
  zh/monitor-a-dm-cluster.md
  zh/overview.md
  zh/relay-log.md
  zh/usage-scenario-master-slave-switch.md
Labels: require-LGT1, status/PTAL, status/can-merge, translation/welcome, v2.0

#230 zh: remove contents about "enable-heartbeat" and "同步延迟监控"
  zh/TOC.md
  zh/_index.md
  zh/feature-online-ddl-scheme.md
  zh/glossary.md
  zh/key-features.md
  zh/performance-test.md
  zh/task-configuration-file-full.md
Labels: require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing, v2.0

#235 zh: fix contents of quick-start
  zh/quick-start-create-task.md
  zh/quick-start-with-dm.md
Labels: size/small, status/PTAL, translation/welcome, v2.0

#226 Update Grafana panels
  zh/alert-rules.md
  zh/monitor-a-dm-cluster.md
Labels: size/medium, status/LGT2, status/PTAL, status/can-merge, translation/doing, v2.0

#216 1.0: update docs about reset task and relay log purge
  en/dm-worker-configuration-file-full.md
  en/error-handling.md
  en/faq.md
  en/relay-log.md
Labels: status/LGT2, status/can-merge, translation/from-zh, type/1.0-cherry-pick

#227 zh: add handle-error-sql-statements.md
  zh/TOC.md
  zh/faq.md
  zh/handle-failed-sql-statements.md
  zh/skip-or-replace-abnormal-sql-statements.md
Labels: size/large, status/LGT2, status/PTAL, status/can-merge, translation/doing, v2.0

#213 en: add the doc about upgrading from 1.0 to 2.0 manually
  en/TOC.md
  en/_index.md
  en/manually-upgrade-dm-1.0-to-2.0.md
  en/upgrade-dm-1.0.md
Labels: status/LGT2, status/PTAL, status/can-merge, translation/from-zh, v2.0

#229 zh: add docs about the usage and scenario of `operate-schema`
  zh/TOC.md
  zh/manage-schema.md
  zh/usage-scenario-downstream-more-columns.md
Labels: require-LGT1, size/large, status/LGT1, status/PTAL, status/can-merge, translation/welcome, v2.0

#242 zh: update handle-alerts for newly added panels
  zh/handle-alerts.md
Labels: require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/welcome, v2.0

#243 zh: update error handling
  zh/error-handling.md
Labels: require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/welcome, v2.0

#244 zh: fix *注意* for relay log
  zh/monitor-a-dm-cluster.md
Labels: require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/welcome, v2.0

#241 zh: update docs about shard DDL lock
  zh/cluster-operations.md
  zh/dmctl-introduction.md
  zh/manually-handling-sharding-ddl-locks.md
  zh/shard-merge-best-practices.md
Labels: require-LGT1, size/medium, status/LGT1, status/PTAL, status/can-merge, translation/welcome, v2.0

#224 Update usage-scenario-shard-merge.md
  en/usage-scenario-shard-merge.md
  zh/usage-scenario-shard-merge.md
Labels: needs-cherry-pick-1.0, status/LGT2, status/PTAL, status/can-merge, translation/from-zh, type/1.0-cherry-pick

#236 zh: update feature-shard-merge-optimistic.md
  zh/feature-shard-merge-optimistic.md
Labels: size/medium, status/LGT2, status/PTAL, translation/doing, v2.0

#225 Add tiup-dm docs
  zh/TOC.md
  zh/deploy-a-dm-cluster-using-tiup.md
  zh/maintain-dm-using-tiup.md
Labels: size/large, status/LGT2, status/PTAL, translation/doing, v2.0

#248 en: remove contents about DM-portal
  en/TOC.md
  en/dm-portal.md
  en/task-configuration-file-full.md
  zh/task-configuration-file-full.md
Labels: size/small, status/LGT2, status/PTAL, status/can-merge, translation/from-zh, v2.0

#251 en: fix contents about encryption of passwords
  en/feature-online-ddl-scheme.md
  en/migrate-from-mysql-aurora.md
  en/quick-start-create-task.md
  en/replicate-data-using-dm.md
  en/task-configuration-file.md
Labels: size/small, status/LGT2, status/PTAL, status/can-merge, translation/from-zh, v2.0

#233 zh: add enable-tls.md
  zh/TOC.md
  zh/enable-tls.md
  zh/generate-self-signed-certificates.md
Labels: require-LGT1, size/medium, status/LGT1, status/PTAL, status/can-merge, translation/doing, v2.0

#249 en: fix contents of quick-start
  en/quick-start-create-task.md
  en/quick-start-with-dm.md
Labels: size/small, status/LGT2, status/PTAL, status/can-merge, translation/from-zh, v2.0

#252 en: update Grafana panels and add relay log notes
  en/alert-rules.md
  en/monitor-a-dm-cluster.md
Labels: size/medium, status/LGT1, translation/from-zh, v2.0

#255 add `operate-source show`
  en/dmctl-introduction.md
  en/manage-source.md
Labels: require-LGT1, size/small, status/LGT1, translation/from-zh, v2.0

#256 zh: replace the usage of DM-Ansible with TiUP
  zh/TOC.md
  zh/_index.md
  zh/alert-rules.md
  zh/cluster-operations.md
  zh/daily-check.md
  zh/deploy-a-dm-cluster-using-ansible.md
  zh/deploy-a-dm-cluster-using-tiup.md
  zh/dmctl-introduction.md
  zh/error-handling.md
  zh/handle-alerts.md
  zh/maintain-dm-using-tiup.md
  zh/manage-source.md
  zh/manually-upgrade-dm-1.0-to-2.0.md
  zh/migrate-from-mysql-aurora.md
  zh/monitor-a-dm-cluster.md
  zh/relay-log.md
  zh/replicate-data-using-dm.md
  zh/upgrade-dm-1.0.md
Labels: require-LGT1, size/large, status/LGT1, status/PTAL, status/can-merge, translation/doing, v2.0

#257 support using task-file when need task-name
  en/dmctl-introduction.md
  en/pause-task.md
  en/resume-task.md
  en/stop-task.md
  en/task-configuration-file.md
Labels: needs-cherry-pick-1.0, size/small, status/LGT1, translation/from-zh, v1.0, v2.0, version-specific-changes-required

#247 en: update contents about relay
  en/TOC.md
  en/dm-worker-intro.md
  en/monitor-a-dm-cluster.md
  en/overview.md
  en/relay-log.md
  en/usage-scenario-master-slave-switch.md
Labels: size/medium, status/LGT2, status/PTAL, status/can-merge, translation/from-zh, v2.0

#259 zh: update architecture; add new features in DM
  media/dm-architecture-2.0.png
  zh/_index.md
  zh/overview.md
Labels: require-LGT1, size/medium, status/LGT1, status/PTAL, status/can-merge, translation/doing, v2.0

#260 update notes for dmctl
  en/dmctl-introduction.md
Labels: size/small, status/LGT1, translation/from-zh, v2.0

#253 en: add document for optimistic mode sharding merge
  en/feature-shard-merge-optimistic.md
Labels: size/large, status/LGT2, status/PTAL, translation/from-zh, v2.0

#254 en: add docs for the usage and scenario of operate-schema
  en/TOC.md
  en/manage-schema.md
  en/usage-scenario-downstream-more-columns.md
Labels: size/large, status/LGT2, status/PTAL, status/can-merge, translation/from-zh, v2.0

#234 zh: Update migrate-from-mysql-aurora.md
  zh/migrate-from-mysql-aurora.md
Labels: status/LGT2, status/PTAL, status/can-merge, translation/doing, v2.0

#265 en: update error handling descriptions
  en/TOC.md
  en/error-handling.md
Labels: needs-cherry-pick-1.0, size/small, status/LGT1, translation/from-zh

#263 zh: update full export and import for more columns in downstream
  zh/usage-scenario-downstream-more-columns.md
Labels: require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing, v2.0

#261 zh,en: update dmctl command
  en/TOC.md
  en/dmctl-introduction.md
  en/error-handling.md
  en/query-error.md
  en/query-status.md
  en/skip-or-replace-abnormal-sql-statements.md
  zh/TOC.md
  zh/dmctl-introduction.md
  zh/error-handling.md
  zh/query-error.md
  zh/query-status.md
Labels: size/small, status/LGT2, status/PTAL, translation/no-need, v2.0

#267 en: update usage-scenario-downstream-more-columns.md
  en/usage-scenario-downstream-more-columns.md
Labels: size/small, status/LGT2, status/PTAL, status/can-merge, translation/from-zh, v2.0

#264 en, zh: add and update tiup-dm docs
  en/TOC.md
  en/deploy-a-dm-cluster-using-tiup.md
  en/maintain-dm-using-tiup.md
  zh/maintain-dm-using-tiup.md
Labels: size/large, status/LGT1, status/PTAL, translation/from-zh, v2.0

#268 en: remove contents about "enable-heartbeat" and "同步延迟监控"
  en/TOC.md
  en/_index.md
  en/feature-online-ddl-scheme.md
  en/glossary.md
  en/key-features.md
  en/performance-test.md
  en/task-configuration-file-full.md
Labels: size/small, status/LGT2, status/PTAL, status/can-merge, translation/from-zh, v2.0

#272 en: : replace the usage of DM-Ansible with TiUP
  en/TOC.md
  en/_index.md
  en/alert-rules.md
  en/cluster-operations.md
  en/daily-check.md
  en/deploy-a-dm-cluster-using-ansible.md
  en/deploy-a-dm-cluster-using-tiup.md
  en/dmctl-introduction.md
  en/error-handling.md
  en/handle-alerts.md
  en/maintain-dm-using-tiup.md
  en/manage-source.md
  en/manually-upgrade-dm-1.0-to-2.0.md
  en/migrate-from-mysql-aurora.md
  en/monitor-a-dm-cluster.md
  en/relay-log.md
  en/replicate-data-using-dm.md
  en/upgrade-dm-1.0.md
Labels: size/large, status/LGT2, status/PTAL, status/can-merge, translation/from-zh, v2.0

#271 en: update handle-alerts for newly added panels
  en/handle-alerts.md
Labels: require-LGT1, size/small, status/LGT2, status/can-merge, translation/from-zh, v2.0

#262 en: add document for optimistic mode sharding merge
  en/TOC.md
  en/feature-manually-handling-sharding-ddl-locks.md
  en/feature-online-ddl-scheme.md
  en/feature-shard-merge-pessimistic.md
  en/feature-shard-merge.md
  en/glossary.md
  en/key-features.md
  en/overview.md
  en/quick-start-create-task.md
  en/shard-merge-best-practices.md
  en/skip-or-replace-abnormal-sql-statements.md
  en/task-configuration-file-full.md
  zh/TOC.md
Labels: size/large, status/LGT2, status/PTAL, status/can-merge, translation/from-zh, v2.0

#274 en: add security-related documents
  en/TOC.md
  en/enable-tls.md
  en/generate-self-signed-certificates.md
Labels: size/medium, status/LGT1, status/PTAL, translation/from-zh, v2.0

#276 Remove deprecated multi_level_url meta
  en/releases/1.0.2.md
  en/releases/1.0.3.md
  en/releases/1.0.4.md
  en/releases/1.0.5.md
  en/releases/1.0.6.md
  zh/releases/1.0.2.md
  zh/releases/1.0.3.md
  zh/releases/1.0.4.md
  zh/releases/1.0.5.md
  zh/releases/1.0.6.md
Labels: needs-cherry-pick-1.0, require-LGT1, status/LGT1, translation/no-need

#269 en: update docs about shard DDL lock
  en/dmctl-introduction.md
  en/feature-manually-handling-sharding-ddl-locks.md
  en/shard-merge-best-practices.md
Labels: size/medium, status/LGT2, status/require-change, translation/from-zh, v2.0

#279 en: update a file name
  en/TOC.md
  en/_index.md
  en/handle-alerts.md
  en/key-features.md
  en/manually-handling-sharding-ddl-locks.md
  en/overview.md
  en/query-status.md
  en/shard-merge-best-practices.md
Labels: status/LGT1, translation/no-need

#278 *: notices about importing 1.0 cluster with TiUP
  en/maintain-dm-using-tiup.md
  en/manually-upgrade-dm-1.0-to-2.0.md
  zh/maintain-dm-using-tiup.md
  zh/manually-upgrade-dm-1.0-to-2.0.md
Labels: size/small, status/LGT2, status/can-merge, translation/no-need, v2.0

#270 en: update architecture; add new features in DM
  en/_index.md
  en/overview.md
Labels: size/small, status/LGT2, status/PTAL, status/can-merge, translation/from-zh, v2.0

#281 chore: update PDF generator
  .circleci/config.yml
Labels: require-LGT1, status/LGT1, status/can-merge

#291 zh, en: remove improper guide
  en/migrate-from-mysql-aurora.md
  zh/migrate-from-mysql-aurora.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT1, status/PTAL, translation/no-need, v2.0

#292 en: support multiple sources create/stop
  en/manage-source.md
Labels: needs-cherry-pick-2.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/from-zh

#293 en: add description of task config `ignore-checking-items`
  en/precheck.md
  en/task-configuration-file-full.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, require-LGT1, status/LGT1, status/PTAL, status/can-merge, translation/from-zh

#303 zh: update join config
  zh/dm-worker-configuration-file.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT2, translation/doing

#304 Update enable-gtid description
  zh/replicate-data-using-dm.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, size/small, status/LGT2, translation/doing

#294 *: update `remove-meta`
  en/create-task.md
  en/feature-online-ddl-scheme.md
  en/overview.md
  en/task-configuration-file-full.md
  en/task-configuration-file.md
  en/usage-scenario-shard-merge.md
  en/usage-scenario-simple-replication.md
  zh/create-task.md
  zh/feature-online-ddl-scheme.md
  zh/overview.md
  zh/task-configuration-file-full.md
  zh/task-configuration-file.md
  zh/usage-scenario-shard-merge.md
  zh/usage-scenario-simple-replication.md
Labels: needs-cherry-pick-2.0, require-LGT1, status/LGT1, status/PTAL, status/can-merge, translation/no-need

#310 Add warning for import cmd
  zh/maintain-dm-using-tiup.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT2, status/PTAL, translation/doing

#296 Add hints for using plaintext passwords
  zh/quick-start-create-task.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, size/small, status/LGT2, status/PTAL, status/can-merge, translation/doing

#302 zh: Update doc for aurora migration
  zh/deploy-a-dm-cluster-using-tiup.md
  zh/hardware-and-software-requirements.md
  zh/migrate-from-mysql-aurora.md
Labels: needs-cherry-pick-2.0, size/medium, status/LGT2, status/PTAL, status/can-merge, translation/doing

#313 zh, en: align dmctl command usage
  en/dmctl-introduction.md
  en/manually-handling-sharding-ddl-locks.md
  zh/dmctl-introduction.md
  zh/manually-handling-sharding-ddl-locks.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT2, status/PTAL, status/can-merge, translation/no-need

#323 zh, en: modify format of `--advertise-peer-urls` (master)
  en/command-line-flags.md
  zh/command-line-flags.md
Labels: needs-cherry-pick-2.0, status/LGT2, translation/no-need

#321 zh: add notices about import/scale with TiUP; some mirror fix
  zh/maintain-dm-using-tiup.md
Labels: needs-cherry-pick-2.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/doing

#322 zh: add a simpe desc about HA
  zh/_index.md
  zh/overview.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT1, status/PTAL, translation/doing

#307 update topology link
  zh/maintain-dm-using-tiup.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT3, status/PTAL, status/can-merge, translation/doing

#330 Add 14 aliases to fix dead links
  en/dm-upgrade.md
  en/feature-manually-handling-sharding-ddl-locks.md
  en/feature-shard-merge.md
  en/query-status.md
  en/table-selector.md
  zh/cluster-operations.md
  zh/dm-master-configuration-file.md
  zh/error-handling.md
  zh/faq.md
  zh/feature-manually-handling-sharding-ddl-locks.md
  zh/feature-overview.md
  zh/skip-or-replace-abnormal-sql-statements.md
  zh/table-selector.md
  zh/usage-scenario-master-slave-switch.md
Labels: status/LGT1, translation/no-need, type/bug-fix
