Repository pingcap/docs-dm, pull requests merged in 2020-06, with the labels that each got.

#106 zh: add FAQ about adding tables to existing task
  zh/faq.md
Labels: needs-cherry-pick-1.0, translation/doing

#108 add auto label github action
  .github/auto-label.json
  .github/pull_request_template.md
  .github/workflows/auto-label.yml
Labels: needs-cherry-pick-1.0, status/PTAL, translation/no-need

#110 Update pull_request_template.md
  .github/pull_request_template.md
Labels: status/PTAL

#113 *: add release notes for v1.0.6
  en/TOC.md
  en/releases/1.0.6.md
  zh/TOC.md
  zh/releases/1.0.6.md
Labels: needs-cherry-pick-1.0, status/PTAL, translation/no-need

#98 zh: update files in release 1.0
  zh/TOC.md
  zh/alert-rules.md
  zh/dm-upgrade.md
  zh/error-handling.md
  zh/error-system.md
  zh/handle-alerts.md
  zh/handle-performance-issues.md
  zh/monitor-a-dm-cluster.md
  zh/replicate-data-using-dm.md
  zh/troubleshoot-dm.md
Labels: type/1.0-cherry-pick

#112 *: update docs about task config
  en/task-configuration-file-full.md
  zh/task-configuration-file-full.md
Labels: needs-cherry-pick-1.0, status/PTAL, status/can-merge, translation/doing

#103 *: update docs about reset task and relay log purge
  zh/faq.md
  zh/relay-log.md
Labels: translation/welcome

#105 zh: frame special characters with quotes to ensure encryption correctness
  zh/deploy-a-dm-cluster-using-ansible.md
Labels: contribution, needs-cherry-pick-1.0, status/can-merge, translation/doing

#104 1.0: update docs about reset task and relay log purge
  zh/dm-worker-configuration-file-full.md
  zh/faq.md
  zh/relay-log.md
Labels: translation/welcome

#102 zh: refine docs about metrics and monitor
  zh/deploy-a-dm-cluster-using-ansible.md
  zh/handle-performance-issues.md
Labels: needs-cherry-pick-1.0, status/can-merge, translation/welcome

#118 en, zh: update en index and zh list
  en/_index.md
  en/deploy-a-dm-cluster-using-binary.md
  en/online-ddl-scheme.md
  zh/TOC.md
  zh/_index.md
Labels: status/PTAL, status/can-merge, translation/from-zh

#111 zh: update TOC and error-handling.md
  zh/TOC.md
  zh/error-handling.md
Labels: status/PTAL, translation/welcome

#120 add auto assign reviewers github action
  .github/assign-by-files.yml
  .github/workflows/auto-assign.yml
Labels: size/small, status/LGT1, translation/no-need

#125 en: batch add aliases to master branch
  en/_index.md
  en/benchmark-v1-alpha.md
  en/benchmark-v1.0-ga.md
  en/cluster-operations.md
  en/config-overview.md
  en/deploy-a-dm-cluster-using-ansible.md
  en/deploy-a-dm-cluster-using-binary.md
  en/dm-master-configuration-file.md
  en/dm-portal.md
  en/dm-upgrade.md
  en/dm-worker-configuration-file.md
  en/dm-worker-intro.md
  en/error-handling.md
  en/error-system.md
  en/faq.md
  en/feature-manually-handling-sharding-ddl-locks.md
  en/feature-overview.md
  en/feature-shard-merge.md
  en/get-started.md
  en/glossary.md
  en/manage-replication-tasks.md
  en/migrate-from-mysql-aurora.md
  en/monitor-a-dm-cluster.md
  en/online-ddl-scheme.md
  en/overview.md
  en/precheck.md
  en/query-status.md
  en/relay-log.md
  en/releases/1.0.2.md
  en/releases/1.0.3.md
  en/releases/1.0.4.md
  en/releases/1.0.5.md
  en/releases/1.0.6.md
  en/replicate-data-using-dm.md
  en/shard-merge-best-practices.md
  en/skip-or-replace-abnormal-sql-statements.md
  en/source-configuration-file.md
  en/table-selector.md
  en/task-configuration-file-full.md
  en/task-configuration-file.md
  en/troubleshoot-dm.md
  en/usage-scenario-shard-merge.md
  en/usage-scenario-simple-replication.md
Labels: status/PTAL, translation/no-need, translation/welcome

#126 en: batch add aliases to 1.0 branch
  en/_index.md
  en/benchmark-v1-alpha.md
  en/benchmark-v1.0-ga.md
  en/cluster-operations.md
  en/config-overview.md
  en/deploy-a-dm-cluster-using-ansible.md
  en/deploy-a-dm-cluster-using-binary.md
  en/dm-master-configuration-file.md
  en/dm-portal.md
  en/dm-upgrade.md
  en/dm-worker-configuration-file-full.md
  en/dm-worker-configuration-file.md
  en/dm-worker-intro.md
  en/error-handling.md
  en/error-system.md
  en/faq.md
  en/feature-manually-handling-sharding-ddl-locks.md
  en/feature-overview.md
  en/feature-shard-merge.md
  en/get-started.md
  en/glossary.md
  en/manage-replication-tasks.md
  en/migrate-from-mysql-aurora.md
  en/monitor-a-dm-cluster.md
  en/online-ddl-scheme.md
  en/overview.md
  en/precheck.md
  en/query-status.md
  en/relay-log.md
  en/releases/1.0.2.md
  en/releases/1.0.3.md
  en/releases/1.0.4.md
  en/releases/1.0.5.md
  en/releases/1.0.6.md
  en/replicate-data-using-dm.md
  en/shard-merge-best-practices.md
  en/skip-or-replace-abnormal-sql-statements.md
  en/table-selector.md
  en/task-configuration-file-full.md
  en/task-configuration-file.md
  en/troubleshoot-dm.md
  en/usage-scenario-shard-merge.md
  en/usage-scenario-simple-replication.md
Labels: translation/no-need

#127 en: add stable aliases to 1.0 branch files
  en/_index.md
  en/benchmark-v1-alpha.md
  en/benchmark-v1.0-ga.md
  en/cluster-operations.md
  en/config-overview.md
  en/deploy-a-dm-cluster-using-ansible.md
  en/deploy-a-dm-cluster-using-binary.md
  en/dm-master-configuration-file.md
  en/dm-portal.md
  en/dm-upgrade.md
  en/dm-worker-configuration-file-full.md
  en/dm-worker-configuration-file.md
  en/dm-worker-intro.md
  en/error-handling.md
  en/error-system.md
  en/faq.md
  en/feature-manually-handling-sharding-ddl-locks.md
  en/feature-overview.md
  en/feature-shard-merge.md
  en/get-started.md
  en/glossary.md
  en/manage-replication-tasks.md
  en/migrate-from-mysql-aurora.md
  en/monitor-a-dm-cluster.md
  en/online-ddl-scheme.md
  en/overview.md
  en/precheck.md
  en/query-status.md
  en/relay-log.md
  en/releases/1.0.2.md
  en/releases/1.0.3.md
  en/releases/1.0.4.md
  en/releases/1.0.5.md
  en/releases/1.0.6.md
  en/replicate-data-using-dm.md
  en/shard-merge-best-practices.md
  en/skip-or-replace-abnormal-sql-statements.md
  en/table-selector.md
  en/task-configuration-file-full.md
  en/task-configuration-file.md
  en/troubleshoot-dm.md
  en/usage-scenario-shard-merge.md
  en/usage-scenario-simple-replication.md
Labels: translation/no-need

#128 Remove _index/ in the alias
  en/_index.md
Labels: status/PTAL, translation/no-need

#121 en: update black & white list and master/slave
  en/TOC.md
  en/_index.md
  en/cluster-operations.md
  en/config-overview.md
  en/deploy-a-dm-cluster-using-ansible.md
  en/deploy-a-dm-cluster-using-binary.md
  en/dm-portal.md
  en/dm-worker-intro.md
  en/error-handling.md
  en/faq.md
  en/feature-overview.md
  en/get-started.md
  en/glossary.md
  en/manage-replication-tasks.md
  en/migrate-from-mysql-aurora.md
  en/overview.md
  en/relay-log.md
  en/replicate-data-using-dm.md
  en/skip-or-replace-abnormal-sql-statements.md
  en/source-configuration-file.md
  en/task-configuration-file-full.md
  en/task-configuration-file.md
  en/usage-scenario-shard-merge.md
  en/usage-scenario-simple-replication.md
Labels: status/LGT1, translation/welcome

#122 en: add hardware-and-software-requirements.md
  en/TOC.md
  en/hardware-and-software-requirements.md
  zh/hardware-and-software-requirements.md
Labels: status/LGT2, status/can-merge, translation/from-zh

#123 en: add create-task-and-verify.md
  en/TOC.md
  en/create-task-and-verify.md
  en/deploy-a-dm-cluster-using-binary.md
Labels: status/LGT2, translation/from-zh

#136 style: adjust table width
  en/error-handling.md
  en/error-system.md
  zh/error-handling.md
Labels: needs-cherry-pick-1.0, status/PTAL, translation/welcome
