Repository pingcap/docs-dm, pull requests merged in 2020-12, with the labels that each got.

#497 add CLA signing guide
  .github/pull_request_template.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, status/LGT1, status/PTAL, translation/no-need

#498 chore: add script to upload file to s3
  .circleci/config.yml
  scripts/upload.py
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, status/LGT1, translation/no-need

#503 readme: change google translate links to appropriate version
  README.md
Labels: needs-cherry-pick-1.0, status/LGT1, status/PTAL, translation/no-need

#505 Update FAQ
  zh/faq.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, size/small, status/LGT2, status/PTAL, translation/doing

#508 en: add three items in faq.md
  en/faq.md
Labels: needs-cherry-pick-2.0, status/LGT2, status/PTAL, translation/from-zh

#510 Update faq.md
  zh/faq.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT2, status/PTAL, status/can-merge, translation/doing

#511 Add 3 aliases to fix broken links
  en/error-handling.md
  en/task-configuration-file.md
  zh/quick-start-with-dm.md
Labels: require-LGT1, status/LGT1, status/can-merge, translation/no-need, type/bug-fix

#513 Add a case of safe-mode enabled
  zh/glossary.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, status/LGT2, status/PTAL, translation/doing

#514 en: Update faq.md
  en/faq.md
Labels: needs-cherry-pick-2.0, status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#523 *: add some faq
  zh/faq.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, status/LGT2, status/PTAL, translation/doing

#524 zh,en: add release notes for 2.0.1
  en/TOC.md
  en/releases/2.0.1.md
  zh/TOC.md
  zh/releases/2.0.1.md
Labels: needs-cherry-pick-2.0, status/DNM, status/LGT2, status/PTAL, translation/no-need

#518 zh,en: bring relay log back
  en/handle-alerts.md
  en/monitor-a-dm-cluster.md
  en/relay-log.md
  en/source-configuration-file.md
  zh/handle-alerts.md
  zh/monitor-a-dm-cluster.md
  zh/relay-log.md
  zh/source-configuration-file.md
Labels: needs-cherry-pick-2.0, status/LGT2, status/PTAL, translation/no-need

#517 zh,en: update precheck items
  en/precheck.md
  zh/precheck.md
Labels: needs-cherry-pick-2.0, status/LGT2, status/PTAL, translation/no-need

#516 zh,en: change `sql` to `DDL` for handle-error command
  en/TOC.md
  en/_index.md
  en/faq.md
  en/handle-failed-ddl-statements.md
  en/overview.md
  zh/TOC.md
  zh/_index.md
  zh/faq.md
  zh/handle-failed-ddl-statements.md
  zh/overview.md
Labels: needs-cherry-pick-2.0, status/LGT2, translation/no-need

#515 zh,en: update dmctl commands
  en/dmctl-introduction.md
  zh/dmctl-introduction.md
Labels: needs-cherry-pick-2.0, status/LGT2, status/PTAL, translation/no-need

#532 en: add a case of safe-mode being enabled
  en/glossary.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#538 *: fix examples for initial-cluster
  en/command-line-flags.md
  zh/command-line-flags.md
Labels: needs-cherry-pick-2.0, status/LGT2, status/PTAL, translation/no-need

#537 Add syncer alias
  en/overview.md
  zh/overview.md
Labels: status/LGT1, status/can-merge, translation/no-need
