Repository pingcap/docs-dm, pull requests merged in 2020-11, with the labels that each got.

#473 Update README.md
  README.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, status/PTAL, translation/no-need

#476 en: add google translate links in readme
  README.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, status/LGT1, status/PTAL, translation/no-need

#480 .github: add an action to check stale issues
  .github/workflows/stale.yml
Labels: status/LGT1, translation/no-need

#481 Add 5 aliases to fix broken links
  en/monitor-a-dm-cluster.md
  en/precheck.md
  zh/dm-worker-configuration-file.md
  zh/error-handling.md
  zh/migrate-from-mysql-aurora.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#482 Add 4 aliases to fix broken links
  en/manage-migration-tasks.md
  zh/deploy-a-dm-cluster-using-ansible.md
  zh/dm-upgrade.md
  zh/dm-worker-configuration-file.md
Labels: translation/no-need, type/bug-fix

#483 *: remove a notice for column-mapping
  en/feature-overview.md
  zh/feature-overview.md
Labels: status/LGT1, status/PTAL, translation/no-need

#484 Media: Update optimistic-ddl-flow.png
  media/optimistic-ddl-flow.png
Labels: needs-cherry-pick-2.0, status/LGT1, translation/no-need

#486 readme: add google translate links of French and Korean
  README.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, status/LGT1, status/PTAL, translation/no-need

#487 CI: update conflicts check to support all file formats except for images
  .github/workflows/ci.yaml
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, status/LGT1, status/PTAL, translation/no-need

#494 chore: remove copyable code snippet when generate PDF
  scripts/merge_by_toc.py
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, status/LGT1, translation/no-need
