Repository pingcap/docs-dm, pull requests merged in 2020-05, with the labels that each got.

#50 en: update config-overview.md for 2.0
  en/config-overview.md
Labels: priority/P1, translation/from-zh, v2.0

#64 ci: update media.yml
  .github/workflows/media.yml
Labels: needs-cherry-pick-1.0

#66 zh,en: remove mydumper-path config for 2.0
  en/deploy-a-dm-cluster-using-binary.md
  en/dm-portal.md
  en/replicate-data-using-dm.md
  en/task-configuration-file-full.md
  zh/deploy-a-dm-cluster-using-binary.md
  zh/dm-portal.md
  zh/replicate-data-using-dm.md
  zh/task-configuration-file-full.md
Labels: status/LGT1, status/can-merge, v2.0

#68 fix: add closing tag for 'br'
  en/config-overview.md
  en/dm-worker-intro.md
  en/feature-overview.md
  zh/config-overview.md
  zh/dm-worker-intro.md
  zh/feature-overview.md
Labels: translation/done

#70 en, zh: address version support
  en/feature-overview.md
  zh/feature-overview.md
Labels: needs-cherry-pick-1.0, status/LGT1, v2.0

#67 zh: update wording and format in online-ddl-scheme
  zh/faq.md
  zh/feature-online-ddl-scheme.md
Labels: needs-cherry-pick-1.0, status/LGT1, status/can-merge, translation/no-need

#58 en: add doc for online-ddl-scheme
  en/TOC.md
  en/faq.md
  en/online-ddl-scheme.md
  en/task-configuration-file-full.md
Labels: needs-cherry-pick-1.0, size/large, status/PTAL, status/can-merge, translation/from-zh

#74 scripts: add a script to run markdownlint check locally
  scripts/markdownlint
Labels: status/can-merge, translation/no-need

#84 ci.yaml: change the branch scope of the CI check
  .github/workflows/ci.yaml
Labels: special-week, translation/no-need

#75 zh: update TOC
  zh/TOC.md
  zh/alert-rules.md
  zh/command-line-flags.md
  zh/configuration-file.md
  zh/configure-topology.md
  zh/daily-check.md
  zh/deploy-a-dm-cluster-using-tiup.md
  zh/error-codes.md
  zh/get-started.md
  zh/handle-alerts.md
  zh/handle-performance-issues.md
  zh/hardware-and-software-requirements.md
  zh/key-features.md
  zh/licensing.md
  zh/performance.md
  zh/quick-start-with-dm.md
  zh/scale-a-dm-cluster.md
  zh/scenarios.md
  zh/system-configuration-check.md
  zh/tune-configuration.md
Labels: special-week, translation/welcome

#76 zh: add the requirement of software and hardware
  zh/hardware-and-software-requirements.md
Labels: special-week, status/LGT1, status/PTAL, status/require-change, translation/welcome

#78 zh: update documents about error handling
  zh/TOC.md
  zh/error-handling.md
  zh/error-system.md
  zh/troubleshoot-dm.md
Labels: special-week, status/LGT1, status/PTAL, status/can-merge, translation/welcome

#81 zh: add a document about performance handling
  zh/handle-performance-issues.md
Labels: special-week, status/LGT1, status/PTAL, status/can-merge, status/require-change, translation/welcome

#77 zh: add document about creating task and verify
  zh/TOC.md
  zh/create-task-and-verify.md
  zh/deploy-a-dm-cluster-using-binary.md
Labels: special-week, status/LGT2, status/PTAL, status/can-merge, translation/welcome

#80 zh: add quick start doc for dm deployment
  zh/quick-start-with-dm.md
Labels: special-week, status/LGT1, status/PTAL, status/can-merge, status/require-change, translation/welcome

#86 zh: update docs about key features
  zh/TOC.md
  zh/dm-portal.md
  zh/feature-overview.md
  zh/feature-shard-merge.md
  zh/glossary.md
  zh/handle-performance-issues.md
  zh/key-features.md
  zh/overview.md
  zh/shard-merge-best-practices.md
  zh/skip-or-replace-abnormal-sql-statements.md
  zh/task-configuration-file-full.md
  zh/task-configuration-file.md
  zh/usage-scenario-shard-merge.md
  zh/usage-scenario-simple-replication.md
Labels: special-week, status/PTAL, status/can-merge, translation/welcome

#89 zh: add a document about how to optimize config
  zh/tune-configuration.md
Labels: special-week, status/PTAL, translation/welcome

#92 zh: Further update TOC.md
  zh/TOC.md
  zh/cluster-operations.md
  zh/key-features.md
  zh/manage-replication-tasks.md
  zh/manually-handling-sharding-ddl-locks.md
  zh/overview.md
  zh/query-status.md
  zh/shard-merge-best-practices.md
Labels: special-week, status/PTAL, translation/welcome

#87 zh: update dm-upgrade
  zh/dm-upgrade.md
Labels: special-week, status/PTAL, status/can-merge, translation/welcome

#88 zh: add a document about scenarios
  zh/scenarios.md
Labels: special-week, status/PTAL, status/can-merge, translation/welcome

#91 zh: update daily-check.md
  zh/daily-check.md
Labels: special-week, status/LGT2, translation/welcome

#93 zh: update docs about alert rules and handling
  zh/TOC.md
  zh/alert-rules.md
  zh/handle-alerts.md
  zh/monitor-a-dm-cluster.md
  zh/replicate-data-using-dm.md
Labels: special-week, status/LGT1, status/can-merge, translation/welcome

#94 zh: add a doc about command-line-flags and update TOC
  zh/TOC.md
  zh/command-line-flags.md
  zh/configuration-file.md
  zh/configure-topology.md
  zh/error-codes.md
  zh/licensing.md
  zh/system-configuration-check.md
Labels: special-week, status/LGT1, status/can-merge, translation/welcome

#90 zh: add files about manage task
  zh/TOC.md
  zh/config-overview.md
  zh/create-task.md
  zh/dmctl-introduction.md
  zh/manage-replication-tasks.md
  zh/manage-source.md
  zh/overview.md
  zh/pause-task.md
  zh/precheck.md
  zh/query-error.md
  zh/query-status.md
  zh/resume-task.md
  zh/skip-or-replace-abnormal-sql-statements.md
  zh/stop-task.md
Labels: special-week, status/LGT2, translation/welcome

#85 zh: add document about how to do performance test
  zh/TOC.md
  zh/benchmark-v1.0-ga.md
  zh/performance-test.md
  zh/stop-task.md
Labels: special-week, status/LGT2, status/require-change, translation/doing

#95 zh: update TOC and remove empty files
  zh/TOC.md
  zh/deploy-a-dm-cluster-using-tiup.md
  zh/dmctl-introduction.md
  zh/performance.md
  zh/scale-a-dm-cluster.md
Labels: special-week, status/PTAL, translation/welcome

#96 *: make image name unique at the repo level
  en/benchmark-v1-alpha.md
  en/dm-portal.md
  media/en/dm-benchmark-01-en.png
  media/en/dm-benchmark-02-en.png
  media/en/dm-benchmark-03-en.png
  media/en/dm-portal-basicconfig-en.png
  media/en/dm-portal-binlogfilter-1-en.png
  media/en/dm-portal-binlogfilter-2-en.png
  media/en/dm-portal-changetablename-en.png
  media/en/dm-portal-generateconfig-en.png
  media/en/dm-portal-instanceconfig-en.png
  media/en/dm-portal-instanceshow-en.png
  media/en/dm-portal-mergetable-1-en.png
  media/en/dm-portal-mergetable-2-en.png
  media/en/dm-portal-movetodb-1-en.png
  media/en/dm-portal-movetodb-2-en.png
  media/en/dm-portal-movetonewdb-1-en.png
  media/en/dm-portal-movetonewdb-2-en.png
  media/en/dm-portal-reset-en.png
  media/en/dm-portal-revert-en.png
  media/en/dm-portal-tableroute-1-en.png
  media/en/dm-portal-tableroute-2-en.png
  media/zh/dm-portal-basicconfig-zh.png
  media/zh/dm-portal-binlogfilter-1-zh.png
  media/zh/dm-portal-binlogfilter-2-zh.png
  media/zh/dm-portal-changetablename-zh.png
  media/zh/dm-portal-generateconfig-zh.png
  media/zh/dm-portal-instanceconfig-zh.png
  media/zh/dm-portal-instanceshow-zh.png
  media/zh/dm-portal-mergetable-1-zh.png
  media/zh/dm-portal-mergetable-2-zh.png
  media/zh/dm-portal-movetodb-1-zh.png
  media/zh/dm-portal-movetodb-2-zh.png
  media/zh/dm-portal-movetonewdb-1-zh.png
  media/zh/dm-portal-movetonewdb-2-zh.png
  media/zh/dm-portal-reset-zh.png
  media/zh/dm-portal-revert-zh.png
  media/zh/dm-portal-tableroute-1-zh.png
  media/zh/dm-portal-tableroute-2-zh.png
  zh/dm-portal.md
Labels: special-week, status/PTAL, translation/welcome

#101 Update landing page _index.md for TiDB DM
  zh/_index.md
Labels: translation/doing

#99 *: make image name unique at the repo level for release 1.0
  en/benchmark-v1-alpha.md
  en/dm-portal.md
  media/en/dm-benchmark-01-en.png
  media/en/dm-benchmark-02-en.png
  media/en/dm-benchmark-03-en.png
  media/en/dm-portal-basicconfig-en.png
  media/en/dm-portal-binlogfilter-1-en.png
  media/en/dm-portal-binlogfilter-2-en.png
  media/en/dm-portal-changetablename-en.png
  media/en/dm-portal-generateconfig-en.png
  media/en/dm-portal-instanceconfig-en.png
  media/en/dm-portal-instanceshow-en.png
  media/en/dm-portal-mergetable-1-en.png
  media/en/dm-portal-mergetable-2-en.png
  media/en/dm-portal-movetodb-1-en.png
  media/en/dm-portal-movetodb-2-en.png
  media/en/dm-portal-movetonewdb-1-en.png
  media/en/dm-portal-movetonewdb-2-en.png
  media/en/dm-portal-reset-en.png
  media/en/dm-portal-revert-en.png
  media/en/dm-portal-tableroute-1-en.png
  media/en/dm-portal-tableroute-2-en.png
  media/zh/dm-portal-basicconfig-zh.png
  media/zh/dm-portal-binlogfilter-1-zh.png
  media/zh/dm-portal-binlogfilter-2-zh.png
  media/zh/dm-portal-changetablename-zh.png
  media/zh/dm-portal-generateconfig-zh.png
  media/zh/dm-portal-instanceconfig-zh.png
  media/zh/dm-portal-instanceshow-zh.png
  media/zh/dm-portal-mergetable-1-zh.png
  media/zh/dm-portal-mergetable-2-zh.png
  media/zh/dm-portal-movetodb-1-zh.png
  media/zh/dm-portal-movetodb-2-zh.png
  media/zh/dm-portal-movetonewdb-1-zh.png
  media/zh/dm-portal-movetonewdb-2-zh.png
  media/zh/dm-portal-reset-zh.png
  media/zh/dm-portal-revert-zh.png
  media/zh/dm-portal-tableroute-1-zh.png
  media/zh/dm-portal-tableroute-2-zh.png
  zh/dm-portal.md
Labels: type/1.0-cherry-pick
