Repository pingcap/docs-dm, pull requests merged in 2020-03, with the labels that each got.

#1 .github: add pr and issue templates for docs-dm
  .github/ISSUE_TEMPLATE/change-request.md
  .github/ISSUE_TEMPLATE/error-report.md
  .github/ISSUE_TEMPLATE/question.md
  .github/pull_request_template.md
Labels: translation/no-need

#6 zh: refine a doc title and fix dead links
  en/monitor-a-dm-cluster.md
  en/overview.md
  en/precheck.md
  zh/faq.md
  zh/glossary.md
  zh/manage-replication-tasks.md
  zh/skip-or-replace-abnormal-sql-statements.md
Labels: needs-cherry-pick-1.0, translation/no-need

#8 en, zh: add version relation between dm and tidb
  en/_index.md
  en/overview.md
  zh/_index.md
  zh/overview.md
Labels: needs-cherry-pick-1.0, size/small

#12 update pdf title
  scripts/generate_pdf.sh
Labels: needs-cherry-pick-1.0

#11 zh, en: add 4 omitted DM files
  en/TOC.md
  en/benchmark-v1-alpha.md
  en/benchmark-v1.0-ga.md
  en/get-started.md
  media/en/dm-benchmark-01.png
  media/en/dm-benchmark-02.png
  media/en/dm-benchmark-03.png
  zh/TOC.md
  zh/benchmark-v1.0-ga.md
  zh/get-started.md
Labels: needs-cherry-pick-1.0, translation/no-need
