Repository pingcap/docs-dm, pull requests merged in 2020-07, with the labels that each got.

#138 *: add aliases to support early links
  en/deploy-a-dm-cluster-using-ansible.md
  zh/overview.md
Labels: translation/no-need

#139 zh: add aliases to two files
  zh/overview.md
  zh/relay-log.md
Labels: translation/no-need

#119 en: add quick-start-with-dm.md
  en/TOC.md
  en/_index.md
  en/get-started.md
  en/quick-start-with-dm.md
  zh/quick-start-with-dm.md
Labels: status/LGT1, status/PTAL, translation/from-zh, version-split-changes-required

#146 Add scripts to verify anchors
  .github/workflows/ci.yaml
  en/dm-portal.md
  en/relay-log.md
  en/task-configuration-file-full.md
  en/task-configuration-file.md
  en/troubleshoot-dm.md
  hack/verify-link-anchors.sh
  hack/verify-links.sh
  zh/error-handling.md
  zh/faq.md
  zh/glossary.md
  zh/manually-handling-sharding-ddl-locks.md
  zh/task-configuration-file-full.md
Labels: needs-cherry-pick-1.0, status/LGT2, status/PTAL, translation/no-need

#145 zh: add example config for safe-mode
  zh/task-configuration-file-full.md
Labels: needs-cherry-pick-1.0, size/small, status/LGT2, status/can-merge, translation/doing

#135 en: add daily check
  en/TOC.md
  en/daily-check.md
Labels: status/LGT1, status/can-merge, translation/from-zh

#150 add 3 aliases to 3 files to avoid 404 urls in Google
  en/create-task-and-verify.md
  en/daily-check.md
  en/hardware-and-software-requirements.md
Labels: status/LGT2, status/PTAL, translation/no-need

#124 en: add error-handling.md
  en/TOC.md
  en/error-handling.md
  en/error-system.md
  en/troubleshoot-dm.md
  zh/error-handling.md
Labels: needs-cherry-pick-1.0, status/LGT2, status/can-merge, translation/from-zh, version-split-changes-required

#153 en: replace secondary library with secondary database
  en/deploy-a-dm-cluster-using-ansible.md
  en/dm-worker-intro.md
  en/skip-or-replace-abnormal-sql-statements.md
Labels: needs-cherry-pick-1.0, size/small, status/LGT2, status/can-merge, translation/no-need

#141 en: add command-line-flags.md
  en/command-line-flags.md
  zh/command-line-flags.md
Labels: status/LGT1, translation/from-zh

#143 en: update docs about key features and dm-portal.md
  en/TOC.md
  en/_index.md
  en/dm-portal.md
  en/feature-shard-merge.md
  en/glossary.md
  en/key-features.md
  en/overview.md
  en/shard-merge-best-practices.md
  en/skip-or-replace-abnormal-sql-statements.md
  en/task-configuration-file-full.md
  en/task-configuration-file.md
  en/usage-scenario-shard-merge.md
  en/usage-scenario-simple-replication.md
  zh/key-features.md
Labels: follow-up, status/LGT2, status/can-merge, translation/from-zh

#147 en: fix wrong section number
  en/feature-manually-handling-sharding-ddl-locks.md
Labels: status/LGT1, status/can-merge, translation/no-need

#159 en: fix wrong section number (#147)
  en/feature-manually-handling-sharding-ddl-locks.md
Labels: require-LGT1, status/LGT2, status/can-merge, translation/doing

#144 en,zh: update handle conflicts of auto-increment primary key
  en/shard-merge-best-practices.md
  zh/shard-merge-best-practices.md
Labels: needs-cherry-pick-1.0, status/LGT2, status/PTAL, status/can-merge, translation/no-need

#134 en: add a document about scenarios
  en/scenarios.md
Labels: follow-up, status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#156 zh, en: add missing task config
  en/task-configuration-file-full.md
  zh/task-configuration-file-full.md
Labels: contribution, status/LGT1, status/can-merge, translation/done

#162 chore: update PDF name
  .circleci/config.yml
Labels: status/LGT1, translation/no-need

#163 zh: fix two bugs in handle-performance-issues.md
  zh/handle-performance-issues.md
Labels: needs-cherry-pick-1.0, status/LGT1, translation/done

#142 en: add handle-performance-issues.md
  en/deploy-a-dm-cluster-using-ansible.md
  en/handle-performance-issues.md
Labels: needs-cherry-pick-1.0, status/LGT2, status/can-merge, translation/from-zh

#131 en: add document about how to do performance test
  en/benchmark-v1.0-ga.md
  en/performance-test.md
Labels: status/LGT2, status/can-merge, translation/from-zh

#132 en: add handle-alerts.md and alert-rules.md
  en/alert-rules.md
  en/handle-alerts.md
  en/monitor-a-dm-cluster.md
  en/replicate-data-using-dm.md
Labels: needs-cherry-pick-1.0, status/LGT2, status/PTAL, translation/from-zh

#133 en: Update TOC.md
  en/TOC.md
Labels: status/LGT2, status/PTAL, translation/from-zh

#130 en: add tune-configuration.md and update dm-upgrade.md
  en/TOC.md
  en/dm-upgrade.md
  en/tune-configuration.md
Labels: contribution, status/LGT1, translation/from-zh

#167 disable 2 github actions
  .github/workflows/auto-assign.yml
  .github/workflows/auto-label.yml
Labels: needs-cherry-pick-1.0, status/LGT1, translation/no-need

#169 zh: add `clean-dump-file` configuration (release-1.0)
  zh/task-configuration-file-full.md
Labels: status/LGT2, translation/doing

#170 zh: add `clean-dump-file` configuration (dev)
  zh/task-configuration-file-full.md
Labels: status/LGT2, translation/doing

#171 zh: support multiple sources create/stop
  zh/manage-source.md
Labels: status/LGT2, status/can-merge, translation/doing

#172 zh,en: add task-configuration-file-full to TOC
  en/TOC.md
  zh/TOC.md
Labels: needs-cherry-pick-1.0, status/LGT3, status/can-merge, translation/no-need

#174 an: fix dead link
  zh/task-configuration-file-full.md
Labels: status/LGT1

#175 delete github action config files
  .github/assign-by-files.yml
  .github/auto-label.json
  .github/workflows/auto-assign.yml
  .github/workflows/auto-label.yml
Labels: needs-cherry-pick-1.0, status/LGT1, translation/no-need

#155 zh: add document for optimistic mode sharding merge
  media/optimistic-ddl-example-1.png
  media/optimistic-ddl-example-10.png
  media/optimistic-ddl-example-2.png
  media/optimistic-ddl-example-3.png
  media/optimistic-ddl-example-4.png
  media/optimistic-ddl-example-5.png
  media/optimistic-ddl-example-6.png
  media/optimistic-ddl-example-7.png
  media/optimistic-ddl-example-8.png
  media/optimistic-ddl-example-9.png
  media/optimistic-ddl-fail-example-1.png
  media/optimistic-ddl-fail-example-2.png
  media/optimistic-ddl-fail-example-3.png
  media/optimistic-ddl-flow.png
  zh/feature-online-ddl-scheme.md
  zh/feature-shard-merge-optimistic.md
  zh/feature-shard-merge-pessimistic.md
  zh/feature-shard-merge.md
  zh/glossary.md
  zh/key-features.md
  zh/manually-handling-sharding-ddl-locks.md
  zh/overview.md
  zh/quick-start-create-task.md
  zh/shard-merge-best-practices.md
  zh/skip-or-replace-abnormal-sql-statements.md
  zh/task-configuration-file-full.md
Labels: status/LGT2, status/PTAL, status/can-merge, translation/welcome

#179 zh: update black-white-list to block-allow-list
  zh/TOC.md
  zh/_index.md
  zh/dm-portal.md
  zh/dmctl-introduction.md
  zh/error-handling.md
  zh/faq.md
  zh/glossary.md
  zh/key-features.md
  zh/migrate-from-mysql-aurora.md
  zh/overview.md
  zh/performance-test.md
  zh/quick-start-create-task.md
  zh/replicate-data-using-dm.md
  zh/scenarios.md
  zh/skip-or-replace-abnormal-sql-statements.md
  zh/task-configuration-file-full.md
  zh/task-configuration-file.md
  zh/usage-scenario-shard-merge.md
  zh/usage-scenario-simple-replication.md
Labels: status/LGT2

#183 zh: Add an alias to fix dead link
  zh/usage-scenario-simple-replication.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#177 zh: add description of task config `ignore-checking-items`
  zh/precheck.md
  zh/task-configuration-file-full.md
Labels: require-LGT1, status/LGT1, status/can-merge, translation/doing, type/1.0-cherry-pick

#184 en: add `clean-dump-file` configuration
  en/task-configuration-file-full.md
Labels: needs-cherry-pick-1.0, status/LGT1, translation/from-zh, version-specific-changes-required

#188 zh: add description of task config `ignore-checking-items` (#177)
  zh/precheck.md
  zh/task-configuration-file-full.md
Labels: require-LGT1, status/LGT1, translation/doing

#186 zh: update black-white-list to block-allow-list
  zh/TOC.md
  zh/_index.md
  zh/deploy-a-dm-cluster-using-binary.md
  zh/dm-portal.md
  zh/error-handling.md
  zh/faq.md
  zh/feature-overview.md
  zh/get-started.md
  zh/glossary.md
  zh/manage-replication-tasks.md
  zh/migrate-from-mysql-aurora.md
  zh/overview.md
  zh/replicate-data-using-dm.md
  zh/skip-or-replace-abnormal-sql-statements.md
  zh/task-configuration-file-full.md
  zh/task-configuration-file.md
  zh/usage-scenario-shard-merge.md
  zh/usage-scenario-simple-replication.md
Labels: status/LGT1, translation/from-en, type/1.0-cherry-pick

#182 en: add quote to special characters
  en/deploy-a-dm-cluster-using-ansible.md
Labels: needs-cherry-pick-1.0, require-LGT1, status/LGT2, status/can-merge, translation/from-zh

#189 zh: add the doc about upgrading from 1.0 to 2.0 manually
  zh/TOC.md
  zh/_index.md
  zh/manually-upgrade-dm-1.0-to-2.0.md
  zh/upgrade-dm-1.0.md
Labels: status/LGT1, translation/doing

#190 update source configuration to YAML
  zh/config-overview.md
  zh/manage-source.md
  zh/quick-start-create-task.md
  zh/replicate-data-using-dm.md
  zh/source-configuration-file.md
Labels: status/LGT2, status/can-merge, translation/doing

#193 *: rename a doc
  en/TOC.md
  en/_index.md
  en/faq.md
  en/feature-online-ddl-scheme.md
  en/key-features.md
  en/scenarios.md
  en/task-configuration-file-full.md
  zh/task-configuration-file-full.md
Labels: needs-cherry-pick-1.0, status/LGT2, status/can-merge, translation/no-need, version-specific-changes-required

#178 zh, en: update error-handling.md
  en/error-handling.md
  zh/error-handling.md
Labels: status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#180 *: update docs about reset task and relay log purge
  en/faq.md
  en/relay-log.md
Labels: require-LGT1, status/LGT1, status/PTAL, status/can-merge

#199 zh, en: Add a privilege for`enable-heartbeat`
  en/key-features.md
  zh/key-features.md
Labels: needs-cherry-pick-1.0, size/small, status/LGT2, status/can-merge, translation/done
