Repository pingcap/docs-dm, pull requests merged in 2020-10, with the labels that each got.

#399 zh, en: remove duplicate config item
  en/task-configuration-file-full.md
  zh/task-configuration-file-full.md
Labels: needs-cherry-pick-2.0, status/LGT2, status/can-merge, translation/no-need

#401 zh: refine some docs
  zh/deploy-a-dm-cluster-using-binary.md
  zh/deploy-a-dm-cluster-using-tiup.md
  zh/handle-failed-sql-statements.md
  zh/task-configuration-file-full.md
  zh/task-configuration-file.md
Labels: needs-cherry-pick-2.0, status/LGT2, translation/doing

#403 zh: clarify required members number
  zh/deploy-a-dm-cluster-using-binary.md
  zh/deploy-a-dm-cluster-using-tiup-offline.md
  zh/deploy-a-dm-cluster-using-tiup.md
Labels: needs-cherry-pick-2.0, status/LGT2, status/require-change, translation/doing

#406 zh: add more restrictions for shard support
  zh/feature-shard-merge-optimistic.md
  zh/feature-shard-merge-pessimistic.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT2

#405 en: clarify required members number
  en/deploy-a-dm-cluster-using-binary.md
  en/deploy-a-dm-cluster-using-tiup-offline.md
  en/deploy-a-dm-cluster-using-tiup.md
  zh/deploy-a-dm-cluster-using-binary.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#410 zh, en: remove reload CA in enable-tls.md
  en/enable-tls.md
  zh/enable-tls.md
Labels: needs-cherry-pick-2.0, status/LGT2, status/PTAL, translation/no-need

#408 en, zh: refine some docs
  en/deploy-a-dm-cluster-using-binary.md
  en/deploy-a-dm-cluster-using-tiup.md
  en/handle-failed-sql-statements.md
  en/task-configuration-file-full.md
  en/task-configuration-file.md
  zh/handle-failed-sql-statements.md
  zh/task-configuration-file-full.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#416 zh: Update deploy-a-dm-cluster-using-tiup.md
  zh/deploy-a-dm-cluster-using-tiup.md
Labels: first-time-contributor, needs-cherry-pick-1.0, status/LGT2, status/PTAL, translation/no-need

#415 zh: Update deploy-a-dm-cluster-using-tiup.md
  zh/deploy-a-dm-cluster-using-tiup.md
Labels: first-time-contributor, size/small, status/LGT2, status/PTAL, status/can-merge, translation/no-need

#418 zh: update deploy-a-dm-cluster-using-tiup.md
  zh/deploy-a-dm-cluster-using-tiup.md
Labels: status/LGT2, status/PTAL, translation/no-need

#412 en: add more restrictions for shard support
  en/feature-shard-merge-optimistic.md
  en/feature-shard-merge-pessimistic.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#420 Update usage-scenario-simple-migration.md
  zh/TOC.md
  zh/_index.md
Labels: first-time-contributor, needs-cherry-pick-1.0, status/LGT1, status/PTAL, translation/doing

#422 Update usage-scenario-master-slave-switch.md
  en/_index.md
  zh/TOC.md
  zh/_index.md
Labels: first-time-contributor, needs-cherry-pick-1.0, require-LGT1, size/small, status/LGT1, status/PTAL, translation/done

#421 Update migrate-from-mysql-aurora.md
  en/_index.md
  en/migrate-from-mysql-aurora.md
  zh/TOC.md
  zh/_index.md
  zh/migrate-from-mysql-aurora.md
Labels: first-time-contributor, needs-cherry-pick-1.0, require-LGT1, size/small, status/LGT1, status/PTAL, status/can-merge, translation/done

#413 zh: update Dumpling configure
  zh/task-configuration-file-full.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT2, status/require-change, translation/doing

#431 1.0: fix dead link
  zh/get-started.md
Labels: status/LGT1, status/PTAL, translation/no-need

#432 1.0 en: fix dead link
  en/get-started.md
Labels: status/LGT1, status/can-merge, translation/from-zh

#425 en, zh: refine file titles and TOC
  en/TOC.md
  en/_index.md
  en/migrate-from-mysql-aurora.md
  zh/TOC.md
  zh/_index.md
  zh/migrate-from-mysql-aurora.md
Labels: require-LGT1, status/LGT1, status/PTAL, status/can-merge, translation/from-zh

#433 test cherry-picker bot
  en/_index.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-master, status/LGT1

#424 zh, en: update a FAQ
  en/faq.md
  zh/faq.md
Labels: needs-cherry-pick-2.0, status/LGT2, status/PTAL, status/can-merge, translation/no-need

#430 en, zh: update Dumpling config
  en/task-configuration-file-full.md
  en/task-configuration-file.md
  zh/task-configuration-file-full.md
  zh/task-configuration-file.md
Labels: needs-cherry-pick-2.0, status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#438 *, CI: add conflicts check and test files
  .github/workflows/ci.yaml
  hack/check-conflicts.py
Labels: status/LGT1

#442 zh: refine TLS docs; add a FAQ about task upgrade
  zh/enable-tls.md
  zh/faq.md
  zh/generate-self-signed-certificates.md
  zh/maintain-dm-using-tiup.md
  zh/manually-upgrade-dm-1.0-to-2.0.md
Labels: needs-cherry-pick-2.0, size/large, status/LGT1, status/PTAL, translation/doing

#445 zh: update target settings in config file
  zh/task-configuration-file-full.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT2, status/PTAL, translation/doing

#444 zh: update "safe mode"
  zh/glossary.md
  zh/migrate-from-mysql-aurora.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT2, status/PTAL, status/can-merge, translation/doing

#446 *: add an unsupported optimistic shard DDL statement
  en/feature-shard-merge-optimistic.md
  zh/feature-shard-merge-optimistic.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT1, status/PTAL, translation/no-need

#454 en: update safe mode description
  en/glossary.md
  en/migrate-from-mysql-aurora.md
Labels: needs-cherry-pick-2.0, status/LGT1, status/PTAL, translation/from-zh

#457 *: add a note for importing from v1.0
  en/maintain-dm-using-tiup.md
  zh/maintain-dm-using-tiup.md
Labels: needs-cherry-pick-2.0, status/LGT2, status/PTAL, translation/no-need

#453 en: update target settings in config file
  en/task-configuration-file-full.md
Labels: needs-cherry-pick-2.0, require-LGT1, status/LGT1, status/PTAL, status/can-merge, translation/from-zh

#451 en: refine TLS docs; add a FAQ about task upgrade
  en/enable-tls.md
  en/faq.md
  en/generate-self-signed-certificates.md
  en/maintain-dm-using-tiup.md
  en/manually-upgrade-dm-1.0-to-2.0.md
  zh/generate-self-signed-certificates.md
Labels: needs-cherry-pick-2.0, status/LGT2, status/PTAL, translation/from-zh

#456 *: unify names of processing units
  en/benchmark-v1-alpha.md
  en/benchmark-v1.0-ga.md
  en/dm-worker-intro.md
  en/feature-shard-merge-pessimistic.md
  en/glossary.md
  en/migrate-data-using-dm.md
  en/relay-log.md
  en/task-configuration-file-full.md
  en/task-configuration-file.md
  zh/benchmark-v1.0-ga.md
  zh/dm-worker-intro.md
  zh/error-handling.md
  zh/glossary.md
  zh/migrate-data-using-dm.md
  zh/relay-log.md
  zh/task-configuration-file-full.md
  zh/task-configuration-file.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, status/LGT2, status/PTAL, status/can-merge, translation/no-need

#463 *: add release notes for 2.0 GA
  en/TOC.md
  en/releases/2.0.0-ga.md
  zh/TOC.md
  zh/releases/2.0.0-ga.md
Labels: needs-cherry-pick-2.0, status/LGT2, status/PTAL, status/can-merge, translation/no-need

#448 *: update the version from RC to GA for samples
  en/deploy-a-dm-cluster-using-tiup-offline.md
  en/deploy-a-dm-cluster-using-tiup.md
  en/maintain-dm-using-tiup.md
  zh/deploy-a-dm-cluster-using-tiup-offline.md
  zh/deploy-a-dm-cluster-using-tiup.md
  zh/maintain-dm-using-tiup.md
Labels: needs-cherry-pick-2.0, status/LGT2, status/can-merge, translation/no-need

#443 en: add benchmark-v2.0-ga.md and optimize v1.0 benchmark
  en/TOC.md
  en/_index.md
  en/benchmark-v1.0-ga.md
  en/benchmark-v2.0-ga.md
  en/handle-performance-issues.md
Labels: needs-cherry-pick-2.0, status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#441 zh: add benchmark-v2.0-ga.md
  zh/TOC.md
  zh/_index.md
  zh/benchmark-v1.0-ga.md
  zh/benchmark-v2.0-ga.md
  zh/handle-performance-issues.md
Labels: needs-cherry-pick-2.0, size/large, status/LGT2, status/PTAL, status/can-merge, status/require-change, translation/done

#466 zh, en: add stable aliases to 1.0 files that don't exist on 2.0 or above
  en/cluster-operations.md
  en/deploy-a-dm-cluster-using-ansible.md
  en/dm-portal.md
  en/dm-upgrade.md
  en/feature-manually-handling-sharding-ddl-locks.md
  en/feature-overview.md
  en/get-started.md
  en/manage-migration-tasks.md
  en/skip-or-replace-abnormal-sql-statements.md
  en/task-configuration-file-full.md
  zh/cluster-operations.md
  zh/deploy-a-dm-cluster-using-ansible.md
  zh/dm-portal.md
  zh/dm-upgrade.md
  zh/feature-manually-handling-sharding-ddl-locks.md
  zh/feature-overview.md
  zh/get-started.md
  zh/manage-migration-tasks.md
  zh/skip-or-replace-abnormal-sql-statements.md
  zh/task-configuration-file-full.md
Labels: status/LGT1, translation/no-need

#465 *: unify names of processing units
  en/benchmark-v1-alpha.md
  en/benchmark-v1.0-ga.md
  en/deploy-a-dm-cluster-using-binary.md
  en/dm-worker-intro.md
  en/feature-shard-merge.md
  en/migrate-data-using-dm.md
  en/migrate-from-mysql-aurora.md
  en/relay-log.md
  en/task-configuration-file-full.md
  en/task-configuration-file.md
  zh/benchmark-v1.0-ga.md
  zh/deploy-a-dm-cluster-using-binary.md
  zh/dm-worker-intro.md
  zh/migrate-data-using-dm.md
  zh/migrate-from-mysql-aurora.md
  zh/relay-log.md
  zh/task-configuration-file-full.md
  zh/task-configuration-file.md
Labels: status/LGT2, status/PTAL, status/can-merge, translation/no-need

#464 chore: update PDF version
  .circleci/config.yml
Labels: status/DNM, status/LGT1, status/PTAL, translation/no-need

#462 chore: update PDF version
  .circleci/config.yml
Labels: status/DNM, status/LGT1, status/PTAL, translation/no-need
