Repository pingcap/docs-dm, pull requests merged in 2021-09, with the labels that each got.

#756 add more metrics
  zh/monitor-a-dm-cluster.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-2.0, size/XS

#771 .github: fix github action config
  .github/workflows/ci.yaml
Labels: needs-cherry-pick-release-1.0, status/LGT1, status/can-merge, translation/no-need, require-LGT1, needs-cherry-pick-release-2.0, size/XS

#774 chore: remove markdown lint from circleci
  .circleci/config.yml
Labels: needs-cherry-pick-release-1.0, status/LGT1, status/can-merge, translation/no-need, require-LGT1, needs-cherry-pick-release-2.0, size/S

#768 monitor-a-dm-cluster: add more metrics
  en/monitor-a-dm-cluster.md
  zh/monitor-a-dm-cluster.md
Labels: status/LGT2, translation/from-zh, status/can-merge, needs-cherry-pick-release-2.0, size/S

#778 Corrected a typo
  zh/deploy-a-dm-cluster-using-tiup-offline.md
Labels: status/LGT2, status/can-merge, translation/no-need, type/enhancement, needs-cherry-pick-release-2.0, first-time-contributor, size/XS, sig/migrate

#770 fix the cli to solve the error report message problem
  en/manually-handling-sharding-ddl-locks.md
  zh/manually-handling-sharding-ddl-locks.md
Labels: status/LGT2, status/can-merge, translation/no-need, needs-cherry-pick-release-2.0, size/XS

#781 Optimize the annotation of worker-size to avoid ambiguity
  zh/task-configuration-file-full.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-2.0, first-time-contributor, size/S

#783 Optimize the annotation of worker-size to avoid ambiguity
  en/task-configuration-file-full.md
  zh/task-configuration-file-full.md
Labels: status/LGT2, translation/from-zh, status/can-merge, needs-cherry-pick-release-2.0, size/S

#786 Refine online ddl doc
  media/dm-online-ddl-2.png
  media/dm-online-ddl.png
  zh/feature-online-ddl.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-2.0, size/M

#790 zh, en: update release note for v2.0.7
  en/releases/2.0.7.md
  zh/releases/2.0.7.md
Labels: status/LGT2, status/PTAL, status/can-merge, translation/no-need, needs-cherry-pick-release-2.0, size/M

#793 zh,en: update release note 2.0.7
  en/TOC.md
  zh/TOC.md
Labels: status/LGT2, status/can-merge, translation/no-need, needs-cherry-pick-release-2.0, size/XS

#792 chore: remove circleci config
  .circleci/config.yml
Labels: status/LGT2, needs-cherry-pick-release-1.0, status/can-merge, translation/no-need, needs-cherry-pick-release-2.0, size/M

#795 v2.0: remove circleci config
  .circleci/config.yml
Labels: status/LGT2, status/can-merge, translation/no-need, size/M

#796 v1.0: remove circleci config
  .circleci/config.yml
Labels: status/LGT2, status/can-merge, translation/no-need, size/M

#787 faq.md: add 1 FAQ
  en/faq.md
  zh/faq.md
Labels: status/LGT2, status/PTAL, status/can-merge, translation/no-need, needs-cherry-pick-release-2.0, size/M
