Repository pingcap/docs-dm, pull requests merged in 2021-01, with the labels that each got.

#541 Add 3 aliases to fix broken links
  en/benchmark-v1-alpha.md
  en/deploy-a-dm-cluster-using-binary.md
  en/deploy-a-dm-cluster-using-tiup.md
Labels: status/LGT1, translation/no-need, type/bug-fix

#540 en: add 2 faqs and update 1 faq
  en/faq.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, status/LGT2, status/PTAL, translation/from-zh

#544 .github: update stale action version
  .github/workflows/stale.yml
Labels: require-LGT1, status/LGT1, translation/done

#545 chore: update dispatch event type
  .github/workflows/dispatch.yml
Labels: status/LGT1

#548 chore: update CDN refresh cache
  .github/workflows/media.yml
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, status/LGT1, translation/no-need
