Repository pingcap/docs-dm, pull requests merged in 2021-02, with the labels that each got.

#551 faq: update dm docs and faq
  zh/dmctl-introduction.md
  zh/faq.md
  zh/source-configuration-file.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, size/medium, status/LGT2, status/PTAL, translation/doing

#552 Check steps after adding and modifying
  zh/task-configuration-file.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT1, status/PTAL, translation/doing

#553 Increase the inspection steps after operating-source is successful
  zh/manage-source.md
Labels: needs-cherry-pick-2.0, size/small, status/LGT2, status/PTAL, status/require-change, translation/doing

#558 Update quick-start-create-task.md
  zh/quick-start-create-task.md
Labels: first-time-contributor, needs-cherry-pick-2.0, size/small, status/LGT2, status/require-change, translation/doing

#561 Media: update two optimistic ddl example images
  media/optimistic-ddl-example-10.png
  media/optimistic-ddl-example-9.png
Labels: needs-cherry-pick-2.0, status/LGT2, status/PTAL, translation/no-need

#562 en: update SQL statements example in quick-start-create-task.md
  en/quick-start-create-task.md
  zh/quick-start-create-task.md
Labels: needs-cherry-pick-2.0, status/LGT2, translation/from-zh

#566 Fix incorrect SQL statements in quick-start-create-task.md
  en/quick-start-create-task.md
  zh/quick-start-create-task.md
Labels: needs-cherry-pick-2.0, status/LGT2, translation/no-need

#570 en: add information of the `get-config` command
  en/manage-source.md
  en/task-configuration-file.md
Labels: needs-cherry-pick-2.0, status/LGT2, status/PTAL, translation/from-zh

#557 adjust dm docs structure
  media/dm-core-features.png
  zh/TOC.md
  zh/_index.md
  zh/config-overview.md
  zh/deploy-a-dm-cluster-using-tiup-offline.md
  zh/deploy-a-dm-cluster-using-tiup.md
  zh/dm-arch.md
  zh/dmctl-introduction.md
  zh/feature-online-ddl-scheme.md
  zh/glossary.md
  zh/handle-alerts.md
  zh/key-features.md
  zh/maintain-dm-using-tiup.md
  zh/manage-schema.md
  zh/manage-source.md
  zh/manually-upgrade-dm-1.0-to-2.0.md
  zh/migrate-data-using-dm.md
  zh/overview.md
  zh/quick-start-with-dm.md
  zh/scenarios.md
  zh/shard-merge-best-practices.md
  zh/task-configuration-file-full.md
  zh/task-configuration-guide.md
  zh/usage-scenario-shard-merge.md
  zh/usage-scenario-simple-migration.md
Labels: first-time-contributor, needs-cherry-pick-2.0, size/large, status/LGT2, status/can-merge, translation/doing

#573 refine dm docs structure
  zh/dm-arch.md
  zh/quick-start-with-dm.md
  zh/task-configuration-guide.md
  zh/usage-scenario-shard-merge.md
Labels: needs-cherry-pick-2.0, status/LGT2, status/can-merge, translation/doing
