Repository pingcap/docs-dm, pull requests merged in 2021-11, with the labels that each got.

#820 adjust TOC to fix a docs website build error
  en/TOC.md
  en/quick-create-migration-task.md
  en/usage-scenario-shard-merge.md
  zh/TOC.md
  zh/quick-create-migration-task.md
  zh/usage-scenario-downstream-more-columns.md
  zh/usage-scenario-incremental-migration.md
  zh/usage-scenario-shard-merge.md
  zh/usage-scenario-simple-migration.md
Labels: status/LGT2, status/can-merge, translation/no-need, needs-cherry-pick-release-2.0, size/M

#812 zh: add openapi doc
  zh/TOC.md
  zh/open-api.md
Labels: status/LGT2, translation/doing, status/can-merge, size/XXL

#824 chore: stop building temporary
  .github/pull_request_template.md
  .github/workflows/dispatch.yml
Labels: status/LGT2, status/can-merge, translation/no-need, size/S

#823 zh,en: add compact and multiple-rows for v5.3.0
  en/glossary.md
  en/task-configuration-file-full.md
  en/usage-scenario-incremental-migration.md
  zh/glossary.md
  zh/task-configuration-file-full.md
  zh/usage-scenario-incremental-migration.md
Labels: status/LGT2, status/can-merge, translation/no-need, size/M

#826 zh,en: add benchmark report for v5.3.0
  en/TOC.md
  en/benchmark-v5.3.0.md
  zh/TOC.md
  zh/benchmark-v5.3.0.md
Labels: status/LGT2, status/PTAL, status/can-merge, translation/no-need, size/XL

#825 fix release version and _index
  CONTRIBUTING.md
  README.md
  en/TOC.md
  en/_index.md
  en/deploy-a-dm-cluster-using-binary.md
  en/faq.md
  en/key-features.md
  en/maintain-dm-using-tiup.md
  en/manually-upgrade-dm-1.0-to-2.0.md
  en/quick-start-with-dm.md
  en/task-configuration-file-full.md
  en/task-configuration-file.md
  en/upgrade-dm-1.0.md
  zh/TOC.md
  zh/_index.md
  zh/deploy-a-dm-cluster-using-binary.md
  zh/faq.md
  zh/maintain-dm-using-tiup.md
  zh/manually-upgrade-dm-1.0-to-2.0.md
  zh/quick-start-with-dm.md
  zh/task-configuration-file.md
  zh/upgrade-dm-1.0.md
Labels: status/LGT2, status/can-merge, translation/no-need, size/XXL, needs-cherry-pick-release-5.3

#831 chore: list as the first child in TOC
  en/TOC.md
  zh/TOC.md
Labels: needs-cherry-pick-release-1.0, status/LGT1, status/can-merge, translation/no-need, require-LGT1, needs-cherry-pick-release-2.0, size/L, needs-cherry-pick-release-5.3

#835 *: fix openapi json example
  en/open-api.md
  zh/open-api.md
Labels: status/LGT2, status/can-merge, translation/no-need, size/M, needs-cherry-pick-release-5.3

#827 zh/en: add 5.3.0 release note
  en/TOC.md
  en/releases/5.3.0.md
  zh/TOC.md
  zh/releases/5.3.0.md
Labels: status/LGT2, status/PTAL, status/can-merge, translation/no-need, size/L, needs-cherry-pick-release-5.3

#839 chore: update generate pdf scripts
  scripts/merge_by_toc.py
Labels: status/LGT2, status/can-merge, translation/no-need, size/S

#838 update the index.md for 5.3
  en/TOC.md
  en/_index.md
  zh/TOC.md
  zh/_index.md
Labels: status/LGT2, status/can-merge, translation/no-need, size/S, needs-cherry-pick-release-5.3

#819 zh,en: make the description clearer on how to use the configs
  en/feature-online-ddl.md
  en/key-features.md
  en/task-configuration-file-full.md
  en/task-configuration-guide.md
  zh/faq.md
  zh/feature-online-ddl.md
  zh/key-features.md
  zh/task-configuration-file-full.md
  zh/task-configuration-guide.md
Labels: status/LGT2, status/can-merge, translation/no-need, needs-cherry-pick-release-2.0, size/M, needs-cherry-pick-release-5.3

#846 chore: update TOC format
  zh/TOC.md
Labels: status/LGT1, status/can-merge, translation/no-need, size/XS

#830 chore: update CI config in release-5.3
  .github/workflows/ci.yaml
  .github/workflows/dispatch.yml
Labels: status/LGT1, status/can-merge, translation/no-need, require-LGT1, size/S
