Repository pingcap/docs-dm, pull requests merged in 2021-08, with the labels that each got.

#732 zh, en: add `is-sharding` config item
  en/task-configuration-file-full.md
  zh/task-configuration-file-full.md
Labels: needs-cherry-pick-release-2.0, size/XS, status/LGT2, status/can-merge, translation/no-need

#749 chore: lock lint plugin versions
  hack/verify-link-anchors.sh
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-2.0, size/XS, status/LGT2, status/can-merge, translation/no-need

#754 zh, en: update release note for v2.0.6
  en/TOC.md
  en/deploy-a-dm-cluster-using-tiup-offline.md
  en/deploy-a-dm-cluster-using-tiup.md
  en/maintain-dm-using-tiup.md
  en/releases/2.0.6.md
  zh/TOC.md
  zh/deploy-a-dm-cluster-using-tiup-offline.md
  zh/deploy-a-dm-cluster-using-tiup.md
  zh/maintain-dm-using-tiup.md
  zh/releases/2.0.6.md
Labels: status/LGT2, status/PTAL, status/can-merge, translation/no-need, needs-cherry-pick-release-2.0, size/M

#757 unify expressions to make sure document consistency
  zh/TOC.md
  zh/_index.md
  zh/quick-create-migration-task.md
  zh/quick-start-create-source.md
  zh/quick-start-with-dm.md
  zh/usage-scenario-downstream-more-columns.md
  zh/usage-scenario-incremental-migration.md
  zh/usage-scenario-shard-merge.md
  zh/usage-scenario-simple-migration.md
Labels: status/LGT2, translation/doing, status/can-merge, needs-cherry-pick-release-2.0, size/M

#748 update toc.md, shard-merge.md, add incremental data migration document
  en/TOC.md
  en/_index.md
  en/migrate-data-using-dm.md
  en/quick-create-migration-task.md
  en/quick-start-create-source.md
  en/quick-start-with-dm.md
  en/shard-merge-best-practices.md
  en/task-configuration-file-full.md
  en/task-configuration-file.md
  en/usage-scenario-downstream-more-columns.md
  en/usage-scenario-incremental-migration.md
  en/usage-scenario-shard-merge.md
  en/usage-scenario-simple-migration.md
  zh/quick-start-with-dm.md
  zh/usage-scenario-downstream-more-columns.md
Labels: status/LGT2, translation/from-zh, status/can-merge, needs-cherry-pick-release-2.0, size/XXL

#752 faq.md: add proxy question
  en/faq.md
Labels: status/LGT2, needs-cherry-pick-release-1.0, translation/from-zh, status/can-merge, needs-cherry-pick-release-2.0, size/S

#753 add usage for expression filter
  en/TOC.md
  en/feature-expression-filter.md
  en/overview.md
  en/task-configuration-file-full.md
  zh/feature-expression-filter.md
Labels: status/LGT2, translation/from-zh, status/can-merge, size/L
