Repository pingcap/docs-dm, pull requests merged in 2021-03, with the labels that each got.

#576 zh: update relay log related operation
  zh/handle-alerts.md
  zh/relay-log.md
Labels: needs-cherry-pick-2.0, status/LGT2, status/PTAL, translation/doing

#567 [2.0.2] zh: add two keepalive config in worker config file
  zh/dm-worker-configuration-file.md
Labels: needs-cherry-pick-2.0, status/LGT2, translation/done

#563 [2.0.2] zh: source level filter support
  zh/key-features.md
  zh/source-configuration-file.md
Labels: needs-cherry-pick-2.0, status/LGT1, translation/done

#569 [2.0.2] zh: add an alerting rule
  zh/handle-alerts.md
Labels: needs-cherry-pick-2.0, status/DNM, status/LGT2, status/PTAL, translation/done

#560 [2.0.2] zh, en: update dmctl help message
  en/dmctl-introduction.md
  zh/dmctl-introduction.md
Labels: needs-cherry-pick-2.0, status/LGT1, translation/no-need

#582 CI: add file format lint script to check manual line breaks and file encoding
  .github/workflows/ci.yaml
  en/handle-alerts.md
  hack/check-conflicts.py
  hack/check-tags.py
  zh/error-handling.md
  zh/task-configuration-file.md
  zh/upgrade-dm-1.0.md
  zh/usage-scenario-shard-merge.md
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, status/LGT1, status/PTAL, translation/no-need

#580 [2.0.2] en: add two keepalive config in worker config file
  en/dm-worker-configuration-file.md
Labels: needs-cherry-pick-2.0, status/DNM, status/LGT2, translation/from-zh

#579 [2.0.2] en: source level filter support
  en/key-features.md
  en/source-configuration-file.md
Labels: needs-cherry-pick-2.0, size/S, status/LGT2, status/can-merge, translation/from-zh

#591 .github: delete stale workflow
  .github/workflows/stale.yml
Labels: size/S, status/LGT2, status/can-merge, translation/no-need

#594 zh: update faq from oncall issue
  zh/faq.md
Labels: needs-cherry-pick-2.0, size/S, status/LGT2, status/can-merge, translation/doing

#596 Update feature-manually-handling-sharding-ddl-locks.md
  zh/feature-manually-handling-sharding-ddl-locks.md
Labels: first-time-contributor, size/XS, status/LGT1, status/PTAL, status/can-merge, translation/doing

#597 Update feature-manually-handling-sharding-ddl-locks.md
  zh/feature-manually-handling-sharding-ddl-locks.md
Labels: first-time-contributor, size/XS, status/LGT1, status/PTAL, status/can-merge, translation/no-need

#598 en: fix a typo in feature-manually-handling-sharding-ddl-locks.md
  en/feature-manually-handling-sharding-ddl-locks.md
Labels: size/XS, status/LGT1, status/PTAL, status/can-merge, translation/from-zh

#600 .github: enable manual rebase
  .github/workflows/rebase.yml
Labels: needs-cherry-pick-1.0, needs-cherry-pick-2.0, require-LGT1, size/S, status/LGT1, status/can-merge, translation/no-need

#577 zh: Update hardware-and-software-requirements.md
  zh/hardware-and-software-requirements.md
Labels: needs-cherry-pick-2.0, status/LGT2, status/PTAL, status/can-merge, translation/doing
