Repository pingcap/docs-dm, pull requests merged in 2021-12, with the labels that each got.

#848 Refine description in dm index page
  en/TOC.md
  en/_index.md
  en/releases/5.3.0.md
  zh/TOC.md
  zh/_index.md
  zh/releases/5.3.0.md
Labels: status/LGT2, status/can-merge, translation/no-need, type/enhancement, size/M, needs-cherry-pick-release-5.3

#850 .github: add external link checker
  .github/exclude-links.txt
  .github/workflows/link-check.yaml
  .github/workflows/link.yaml
  README.md
Labels: status/LGT1, status/can-merge, translation/no-need, require-LGT1, size/M

#851 Fix format in TOC
  en/TOC.md
Labels: status/LGT2, status/can-merge, translation/no-need, type/bug-fix, needs-cherry-pick-release-2.0, first-time-contributor, size/XS, needs-cherry-pick-release-5.3

#856 chore: update dispatch for latest docs site
  .github/workflows/dispatch.yml
Labels: status/LGT2, needs-cherry-pick-release-1.0, status/can-merge, translation/no-need, needs-cherry-pick-release-2.0, size/M, needs-cherry-pick-release-5.3

#864 replace a video for the overview page
  zh/overview.md
Labels: status/LGT2, status/can-merge, translation/no-need, first-time-contributor, size/XS, needs-cherry-pick-release-5.3

#863 update description of relay log
  zh/relay-log.md
  zh/source-configuration-file.md
Labels: status/LGT2, translation/doing, status/can-merge, type/bug-fix, needs-cherry-pick-release-2.0, size/XS, sig/migrate, needs-cherry-pick-release-5.3

#858 changed github.com/pingcap/ticdc to github.com/pingcap/tiflow
  en/_index.md
  en/deploy-a-dm-cluster-using-binary.md
  en/faq.md
  en/open-api.md
  en/releases/5.3.0.md
  zh/_index.md
  zh/deploy-a-dm-cluster-using-binary.md
  zh/faq.md
  zh/open-api.md
  zh/releases/5.3.0.md
Labels: status/LGT2, status/can-merge, missing-translation-status, size/M

#859 changed github.com/pingcap/ticdc to github.com/pingcap/tiflow
  zh/faq.md
Labels: status/LGT2, status/can-merge, translation/no-need, size/XS, sig/migrate

#857 changed github.com/pingcap/ticdc to github.com/pingcap/tiflow
  en/_index.md
  en/deploy-a-dm-cluster-using-binary.md
  en/faq.md
  en/open-api.md
  en/releases/5.3.0.md
  zh/_index.md
  zh/deploy-a-dm-cluster-using-binary.md
  zh/faq.md
  zh/open-api.md
  zh/releases/5.3.0.md
Labels: status/LGT2, status/can-merge, translation/no-need, size/M, sig/migrate

#873 change file mode
  scripts/generate_pdf.sh
Labels: status/LGT2, needs-cherry-pick-release-1.0, status/can-merge, translation/no-need, needs-cherry-pick-release-2.0, size/XS, needs-cherry-pick-release-5.3

#879 repository: add information about the DM doc master branch changes
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
Labels: status/LGT2, needs-cherry-pick-release-1.0, status/can-merge, translation/no-need, needs-cherry-pick-release-2.0, size/S, needs-cherry-pick-release-5.3
