Repository pingcap/docs-dm, pull requests merged in 2021-06, with the labels that each got.

#686 zh: add some introduction in `overview.md`
  zh/overview.md
Labels: needs-cherry-pick-release-2.0, size/S, status/LGT2, status/can-merge, translation/doing

#688 readme: add contributing guide
  CONTRIBUTING.md
  README.md
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-2.0, size/L, status/LGT2, status/can-merge, translation/no-need

#687 Update quick start
  zh/TOC.md
  zh/_index.md
  zh/quick-create-migration-task.md
  zh/quick-start-create-source.md
  zh/quick-start-with-dm.md
  zh/usage-scenario-downstream-more-columns.md
  zh/usage-scenario-incremental-migration.md
  zh/usage-scenario-shard-merge.md
  zh/usage-scenario-simple-migration.md
Labels: needs-cherry-pick-release-2.0, size/XXL, status/LGT2, status/can-merge, translation/doing

#704 *: update dmctl document about usage
  en/dmctl-introduction.md
  en/enable-tls.md
  en/quick-start-create-task.md
  en/quick-start-with-dm.md
  zh/dmctl-introduction.md
  zh/enable-tls.md
  zh/quick-start-create-source.md
  zh/quick-start-create-task.md
  zh/quick-start-with-dm.md
Labels: needs-cherry-pick-release-2.0, size/M, status/LGT2, status/can-merge, translation/no-need

#706 zh, en: add 2.0.4 release note
  en/TOC.md
  en/releases/2.0.4.md
  zh/TOC.md
  zh/releases/2.0.4.md
Labels: needs-cherry-pick-release-2.0, size/M, status/LGT2, status/PTAL, status/can-merge, translation/no-need

#707 zh,en: update safe-mode duration
  en/faq.md
  en/glossary.md
  en/task-configuration-file-full.md
  zh/faq.md
  zh/glossary.md
  zh/task-configuration-file-full.md
  zh/usage-scenario-incremental-migration.md
Labels: needs-cherry-pick-release-2.0, size/S, status/LGT2, status/can-merge, translation/no-need

#691 [2.0.4] dmctl: support read master addr from env
  en/dmctl-introduction.md
  zh/dmctl-introduction.md
Labels: needs-cherry-pick-release-2.0, size/XS, status/LGT2, status/can-merge, translation/no-need

#711 zh, en: update release note for v1.0.7
  en/TOC.md
  en/releases/1.0.7.md
  zh/TOC.md
  zh/releases/1.0.7.md
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-2.0, size/S, status/LGT2, status/PTAL, status/can-merge, translation/no-need
