Repository pingcap/docs-dm, pull requests merged in 2021-07, with the labels that each got.

#715 en: add some introduction in overview.md
  en/overview.md
Labels: needs-cherry-pick-release-2.0, size/S, status/LGT2, status/can-merge, translation/from-zh

#717 dmctl-introducation: fix typo
  en/dmctl-introduction.md
  zh/dmctl-introduction.md
Labels: needs-cherry-pick-release-2.0, size/XS, status/LGT2, status/can-merge, translation/no-need

#698 zh: add detailed checks and steps for shard-merge scenario
  zh/shard-merge-best-practices.md
  zh/usage-scenario-shard-merge.md
Labels: needs-cherry-pick-release-2.0, size/L, status/LGT2, status/can-merge, translation/doing

#721 Specify an ip for master addr in configuration
  en/deploy-a-dm-cluster-using-binary.md
  zh/deploy-a-dm-cluster-using-binary.md
Labels: missing-translation-status, size/XS, status/LGT2, status/can-merge

#724 PR template: Optimize description of the master branch in the PR template
  .github/pull_request_template.md
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-2.0, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/no-need

#723 add proxy question
  zh/faq.md
Labels: first-time-contributor, needs-cherry-pick-release-1.0, needs-cherry-pick-release-2.0, size/S, status/LGT2, status/can-merge, translation/doing

#729 zh: add usage for expression filter
  zh/TOC.md
  zh/feature-expression-filter.md
  zh/overview.md
  zh/task-configuration-file-full.md
Labels: needs-cherry-pick-release-2.0, requires-version-specific-changes, size/L, status/LGT2, status/can-merge, translation/doing

#737 zh, en: add default value for --flush flag for v2.0.5
  en/manage-schema.md
  zh/manage-schema.md
Labels: needs-cherry-pick-release-2.0, size/XS, status/LGT2, status/PTAL, status/can-merge, translation/no-need

#735 zh, en: add some description about configurations
  en/key-features.md
  en/source-configuration-file.md
  zh/key-features.md
  zh/source-configuration-file.md
Labels: needs-cherry-pick-release-2.0, size/M, status/LGT2, status/can-merge, translation/no-need

#736 zh: add config command for v2.0.5
  zh/TOC.md
  zh/dmctl-introduction.md
  zh/export-import-config.md
  zh/maintain-dm-using-tiup.md
Labels: needs-cherry-pick-release-2.0, size/L, status/LGT2, status/PTAL, status/can-merge, translation/doing

#734 zh, en: update online ddl doc
  en/TOC.md
  en/faq.md
  en/feature-online-ddl.md
  en/key-features.md
  en/scenarios.md
  en/task-configuration-file-full.md
  zh/TOC.md
  zh/faq.md
  zh/feature-online-ddl.md
  zh/key-features.md
  zh/scenarios.md
  zh/task-configuration-file-full.md
Labels: first-time-contributor, size/L, status/LGT2, status/can-merge, translation/no-need

#743 [2.0.5] en: add config command for v2.0.5
  en/TOC.md
  en/dmctl-introduction.md
  en/export-import-config.md
  en/maintain-dm-using-tiup.md
Labels: needs-cherry-pick-release-2.0, size/L, status/LGT2, status/can-merge, translation/from-zh

#741 zh, en: update release note for v2.0.5
  en/TOC.md
  en/releases/2.0.5.md
  zh/TOC.md
  zh/releases/2.0.5.md
Labels: needs-cherry-pick-release-2.0, size/M, status/LGT2, status/PTAL, status/can-merge, translation/no-need
