Repository pingcap/docs-dm, pull requests merged in 2021-05, with the labels that each got.

#633 Update task-configuration-file.md
  zh/task-configuration-file.md
Labels: contribution, needs-cherry-pick-2.0, size/XS, status/LGT2, status/can-merge, status/require-change, translation/doing

#575 zh: add an example for incremental sync
  zh/TOC.md
  zh/_index.md
  zh/key-features.md
  zh/migrate-data-using-dm.md
  zh/performance-test.md
  zh/quick-start-create-task.md
  zh/task-configuration-file-full.md
  zh/task-configuration-file.md
  zh/task-configuration-guide.md
  zh/usage-scenario-incremental-migration.md
  zh/usage-scenario-shard-merge.md
  zh/usage-scenario-simple-migration.md
Labels: needs-cherry-pick-2.0, size/XL, status/LGT2, status/PTAL, status/can-merge, translation/doing

#661 [2.0.3] *: update release note
  en/TOC.md
  en/releases/2.0.2.md
  en/releases/2.0.3.md
  zh/TOC.md
  zh/releases/2.0.2.md
  zh/releases/2.0.3.md
Labels: needs-cherry-pick-2.0, size/M, status/LGT2, status/PTAL, status/can-merge, translation/no-need

#655 zh: update security config requirement in source configuration file
  zh/source-configuration-file.md
Labels: needs-cherry-pick-release-2.0, size/XS, status/LGT2, status/can-merge, translation/doing

#658 zh,en: update dmctl commands for v2.0.3
  en/dmctl-introduction.md
  zh/dmctl-introduction.md
Labels: needs-cherry-pick-release-2.0, size/S, status/LGT2, status/PTAL, status/can-merge, translation/no-need

#663 en: guide user to get dmctl
  en/deploy-a-dm-cluster-using-tiup.md
Labels: needs-cherry-pick-release-2.0, size/XS, status/LGT2, status/can-merge, translation/from-zh

#668 *: add link: deploy dm in k8s
  en/TOC.md
  zh/TOC.md
Labels: needs-cherry-pick-release-1.0, needs-cherry-pick-release-2.0, size/XS, status/LGT2, status/can-merge, translation/no-need

#667 en: update security config requirement in source configuration file
  en/source-configuration-file.md
Labels: first-time-contributor, needs-cherry-pick-release-2.0, size/XS, status/LGT2, status/can-merge, translation/from-zh

#674 zh: fix testdm-task.yaml format
  zh/quick-start-with-dm.md
Labels: contribution, first-time-contributor, needs-cherry-pick-release-2.0, size/S, status/LGT2, status/PTAL, status/can-merge, translation/doing

#660 Update task-configuration-file
  en/task-configuration-file.md
Labels: first-time-contributor, needs-cherry-pick-release-2.0, size/XS, status/LGT2, status/can-merge, translation/from-zh

#678 en: fix testdm-task.yaml format
  en/quick-start-with-dm.md
Labels: needs-cherry-pick-release-2.0, size/S, status/LGT2, status/can-merge, translation/from-zh

#681 feat: add contributor over time graph to README
  README.md
Labels: contribution, first-time-contributor, needs-cherry-pick-release-1.0, needs-cherry-pick-release-2.0, size/XS, status/LGT2, status/can-merge, translation/no-need

#680 *: update patch version to the latest
  en/deploy-a-dm-cluster-using-tiup-offline.md
  en/deploy-a-dm-cluster-using-tiup.md
  en/maintain-dm-using-tiup.md
  zh/deploy-a-dm-cluster-using-tiup-offline.md
  zh/deploy-a-dm-cluster-using-tiup.md
  zh/maintain-dm-using-tiup.md
Labels: needs-cherry-pick-release-2.0, size/M, status/LGT2, status/can-merge, translation/no-need

#690 en: add a missing indent in English TOC to fix abnormal display
  en/TOC.md
Labels: needs-cherry-pick-release-2.0, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/no-need

#692 *: fix yaml indent issues
  en/quick-start-create-task.md
  en/task-configuration-file-full.md
  en/task-configuration-guide.md
  en/usage-scenario-shard-merge.md
  zh/task-configuration-file-full.md
  zh/task-configuration-guide.md
  zh/usage-scenario-shard-merge.md
Labels: needs-cherry-pick-release-2.0, size/L, status/LGT2, status/can-merge, translation/no-need

#679 zh, en: add relay-dir for source-configuration-file
  en/relay-log.md
  en/source-configuration-file.md
  zh/relay-log.md
  zh/source-configuration-file.md
Labels: needs-cherry-pick-release-2.0, size/M, status/LGT2, status/PTAL, status/can-merge, translation/no-need
