Repository pingcap/docs-dm, pull requests merged in 2021-04, with the labels that each got.

#599 adjust some limitation about sharding ddl
  en/feature-shard-merge-pessimistic.md
  zh/feature-shard-merge-pessimistic.md
Labels: needs-cherry-pick-2.0, size/S, status/LGT2, status/PTAL, status/can-merge, translation/no-need

#613 en: fix dead external links
  en/deploy-a-dm-cluster-using-tiup-offline.md
  en/deploy-a-dm-cluster-using-tiup.md
  en/maintain-dm-using-tiup.md
Labels: needs-cherry-pick-2.0, size/S, status/LGT2, status/PTAL, status/can-merge, translation/no-need

#606 [2.0.2] *: update `operate-schema`
  en/manage-schema.md
  media/operate-schema.png
  zh/manage-schema.md
Labels: needs-cherry-pick-2.0, size/M, status/LGT2, status/PTAL, status/can-merge, translation/no-need

#605 [2.0.2] *: add `transfer-source` command
  en/config-overview.md
  en/manage-source.md
  en/manually-upgrade-dm-1.0-to-2.0.md
  en/performance-test.md
  zh/TOC.md
  zh/config-overview.md
  zh/manage-source.md
  zh/manually-upgrade-dm-1.0-to-2.0.md
  zh/performance-test.md
  zh/task-configuration-guide.md
Labels: needs-cherry-pick-2.0, size/XL, status/LGT2, status/PTAL, status/can-merge, translation/no-need

#611 *: update tidb-server download URL
  en/quick-start-create-task.md
  zh/quick-start-create-task.md
Labels: needs-cherry-pick-2.0, size/S, status/LGT2, status/PTAL, status/can-merge, translation/no-need

#608 [2.0.2] zh: add `start-relay` and `stop-relay`
  zh/relay-log.md
Labels: needs-cherry-pick-2.0, size/L, status/LGT2, status/PTAL, status/can-merge, translation/done

#612 [2.0.2] en: add `start-relay` and `stop-relay`
  en/handle-alerts.md
  en/relay-log.md
Labels: needs-cherry-pick-2.0, size/L, status/LGT2, status/PTAL, status/can-merge, translation/from-zh

#614 [2.0.2] *: update release note
  en/TOC.md
  en/releases/2.0.2.md
  zh/TOC.md
  zh/releases/2.0.2.md
Labels: needs-cherry-pick-2.0, size/L, status/LGT2, status/PTAL, status/can-merge, translation/no-need

#622 *: fix a missing space
  en/releases/2.0.2.md
Labels: needs-cherry-pick-2.0, size/XS, status/LGT2, status/can-merge, translation/no-need

#603 guide user to dmctl
  zh/deploy-a-dm-cluster-using-tiup.md
Labels: needs-cherry-pick-2.0, size/XS, status/LGT2, status/PTAL, status/can-merge, translation/doing

#610 *: add constraint for binary deployment
  en/deploy-a-dm-cluster-using-binary.md
  zh/deploy-a-dm-cluster-using-binary.md
Labels: needs-cherry-pick-2.0, size/XS, status/LGT2, status/PTAL, status/can-merge, translation/no-need

#593 faq: update dm docs and add 4 FAQs
  en/faq.md
  en/source-configuration-file.md
Labels: needs-cherry-pick-2.0, require-LGT1, size/L, status/LGT1, status/can-merge, translation/from-zh

#627 Update precheck info about MySQL 8.0 support
  en/migrate-data-using-dm.md
  en/overview.md
  en/precheck.md
Labels: first-time-contributor, needs-cherry-pick-2.0, size/S, status/LGT2, status/PTAL, status/can-merge, translation/doing

#629 Update description for `extra-args`
  zh/migrate-data-using-dm.md
Labels: needs-cherry-pick-2.0, size/XS, status/LGT2, status/PTAL, status/can-merge, translation/doing

#630 Remove the `skip-tz-utc` configuration item
  zh/usage-scenario-simple-migration.md
Labels: needs-cherry-pick-2.0, size/XS, status/LGT2, status/PTAL, status/can-merge, translation/doing

#631 Remove skip-tz-utc parameter
  zh/task-configuration-file-full.md
Labels: needs-cherry-pick-2.0, size/XS, status/LGT2, status/can-merge, translation/doing

#632 Remove the skip-tz-utc configuration item
  zh/usage-scenario-shard-merge.md
Labels: needs-cherry-pick-2.0, size/XS, status/LGT2, status/can-merge, translation/doing

#642 en: update 2 FAQs from oncall issue
  en/faq.md
Labels: needs-cherry-pick-2.0, require-LGT1, size/S, status/LGT1, status/can-merge, translation/from-zh

#640 zh: refine the description of one faq
  zh/faq.md
Labels: needs-cherry-pick-2.0, require-LGT1, size/S, status/LGT1, status/can-merge, translation/from-en

#641 zh: update precheck info about MySQL 8.0 support
  en/overview.md
  en/precheck.md
  zh/deploy-a-dm-cluster-using-tiup-offline.md
  zh/migrate-data-using-dm.md
  zh/overview.md
  zh/precheck.md
Labels: needs-cherry-pick-2.0, require-LGT1, size/M, status/LGT1, status/can-merge, translation/from-en

#643 *: update docs-dm
  en/deploy-a-dm-cluster-using-binary.md
  en/deploy-a-dm-cluster-using-tiup.md
  zh/deploy-a-dm-cluster-using-binary.md
  zh/deploy-a-dm-cluster-using-tiup.md
  zh/quick-start-with-dm.md
Labels: first-time-contributor, needs-cherry-pick-2.0, size/M, status/LGT2, status/can-merge, translation/doing

#639 en: remove the `skip-tz-utc` configuration item and update description of `extra-args`
  en/migrate-data-using-dm.md
  en/task-configuration-file-full.md
  en/usage-scenario-shard-merge.md
  en/usage-scenario-simple-migration.md
Labels: needs-cherry-pick-2.0, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/from-zh

#654 en: update deploy-a-dm-cluster-using-tiup-offline.md
  en/deploy-a-dm-cluster-using-tiup-offline.md
Labels: needs-cherry-pick-2.0, require-LGT1, size/XS, status/LGT1, status/can-merge, translation/from-zh
