Repository pingcap/docs-dm, pull requests merged in 2022-06, with the labels that each got.

#905 add aliases to 5.3 dm benchmark report
  en/dm-benchmark-v5.3.0.md
  zh/dm-benchmark-v5.3.0.md
Labels: translation/done, status/LGT1, status/can-merge, type/bug-fix, require-LGT1, size/XS

#907 ci: add link.yaml
  .github/workflows/link.yaml
Labels: status/LGT1, status/can-merge, translation/no-need, first-time-contributor, size/M

#911 ci: update node version to 16
  .github/workflows/ci.yaml
Labels: status/LGT1, status/can-merge, translation/no-need, require-LGT1, needs-cherry-pick-release-2.0, first-time-contributor, size/XS, needs-cherry-pick-release-5.3

#908 ci: move link.yaml from master to release 5.3
  .github/workflows/link.yaml
Labels: status/LGT2, status/can-merge, translation/no-need, first-time-contributor, size/S
