Repository pingcap/docs-dm, pull requests merged in 2022-01, with the labels that each got.

#878 update description of relay log
  en/dm-source-configuration-file.md
  en/relay-log.md
Labels: status/LGT2, translation/from-zh, status/can-merge, type/bug-fix, needs-cherry-pick-release-2.0, size/XS, sig/migrate

#883 Remove unknown dir config
  en/get-started.md
  zh/get-started.md
Labels: status/LGT2, translation/done, status/can-merge, require-LGT1, size/XS, sig/migrate

#885 adjust timezone config description
  en/task-configuration-file-full.md
  zh/task-configuration-file-full.md
Labels: translation/doing, status/LGT1, status/can-merge, type/enhancement, first-time-contributor, size/XS, sig/migrate

#887 Correct unclear description in feature-online-ddl
  en/feature-online-ddl.md
  zh/feature-online-ddl.md
Labels: translation/done, status/LGT1, status/can-merge, type/bug-fix, size/XS, sig/migrate
